client/src/components/DetailView.js
client/src/components/PropertiesList.js
client/src/components/PropertiesMap.js
client/src/components/PropertiesSummary.js
client/src/containers/HowItWorksPage.js
client/src/styles/DetailView.scss
client/src/styles/spectre.scss
sql/agg_function.sql
sql/create_bldgs_table.sql
sql/registrations_with_contacts.sql

- Reconfigured SQL queries to accommodate new Marshals Evictions data
- Updated tooltips, summary page, list table headers, and "how it works" page 
- removed justfix user data and all references to it
- tweaked aggregate SQL to for new summary information on evictions

Evictions update

---

client/src/components/DetailView.js
client/src/components/PropertiesList.js
client/src/styles/DetailView.scss
sql/create_bldgs_table.sql

This updates the RS to 2017 (and using PLUTO 18v1).
Also some visual tweaks to DetailView snuck in here

Rentstab updates

---

client/src/components/DetailView.js
client/src/styles/LegalFooter.scss

- fixed bug with footer height inconsistency
- encoded social sharing urls
PS: branch based on `full-bbl-url-support` so merge that one first :)

Small tweaks

---

client/src/components/PropertiesSummary.js

refactored auto-generating summary text to work grammatically/contextually in cases with 0 or 1 buildings, units, landlords etc.

Portfolio of one issues

---

.env.sample
client/src/containers/HomePage.js

- added better All Year Management example portfolio
- added optional MailChimp vars to env.sample

Quick fixes

---

.dockerignore
.gitignore

This just makes a few changes to `.gitignore` and `.dockerignore` to make it easier to customize our Docker setup and also make Docker run a bit faster when it's building stuff.

Modify .gitignore and .dockerignore a bit

---

.circleci/config.yml
client/src/components/AddressSearch.test.tsx
client/src/components/AddressSearch.tsx

Fix undefined housenumber bug, add our first front-end test suite

---

client/src/components/APIClient.js
client/src/components/AddressSearch.tsx
client/src/containers/AddressPage.js
client/src/containers/BBLPage.js
client/src/util/geo-autocomplete-base.ts
server/controllers/address.js

This just passes the BBL from the autocomplete's payload on to the server, which just uses it as-is instead of using geoclient.

Avoid using geoclient

---

client/src/components/IndicatorsViz.js

Example: https://whoownswhat.justfix.nyc/address/QUEENS/150-03/88%20AVENUE

fixed bug where DOB permit bars go too high

---

client/package.json
client/public/index.html
client/src/containers/App.js
client/yarn.lock
yarn-error.log

and removed site tag on index.html

added fullstory via react-fullstory module

---

server/controllers/address.js
server/routes.js
server/services/db.js

@0xStarcat, I'm adding this new api route specifically for DAP Portal to use!

Added dap aggregate api

---

client/.env.local.sample
client/src/containers/App.js
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/App.scss

This PR adds a small label to the header of WOW, enabled by an ENV variable, that indicates if the site is our demo/preview site. The styling uses Spectre's label class with some custom css as well.

Added Demo tag

---

client/src/components/PropertiesMap.js
client/src/locales/en/messages.po
client/src/locales/es/messages.po

The "Legend" title on our properties map disappeared by accident in #215. I added it back here!

added map legend title back on desktop

---

client/src/components/LegalFooter.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/LegalFooter.scss

This update refactors the website footer into two columns so that we can show our legal disclaimer.

Add Disclaimer to footer

---

client/src/components/DetailView.js
client/src/components/Indicators.js
client/src/containers/NychaPage.js

This PR adds the ANHD DAP Portal link to all NYCHA pages, and removes the "New" tag.

Updated dap portal links

---

client/src/containers/HomePage.tsx
client/src/styles/HomePage.scss
client/src/styles/spectre.scss

Added a banner calling out our COVID-19 status and pointing people to FAQs about the NYC Eviction Moratorium.

Added Eviction Moratorium banner

---

sql/create_bldgs_table.sql

Oops! By converting to UPPERCASE, we actually overwrote some names that broke connections within the database. This fixes things.

Updated syntax case on buildings table sql

---

client/src/components/ViolationsSummary.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

After merging #236, this PR reconfigures our lingui localization to make sure the page is still properly translated with our pre-existing translations. It also updates our average violation count for the city (which hasn't changed).

Reconfigure localization for new Violations Summary

---

client/src/containers/NotRegisteredPage.js
client/src/containers/NychaPage.js
client/src/styles/Modal.scss
client/src/styles/NotRegisteredPage.scss

This PR adds some simple styling updates to make sure our not registered pages look ok with our Spanish translations.

Fixed spacing issues on not registered pages

---

client/src/styles/NotRegisteredPage.scss

This mini PR fixes an issue where the bounding box on not-registered pages didn't center properly.

Fixed styling issues on not-registered page

---

client/src/containers/HomePage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This hotfix updates the COVID-19 info banner on the home page with more up-to-date info.

Updated covid banner with new info

---

client/src/components/LegalFooter.tsx
client/src/styles/LegalFooter.scss

This PR adds a banner to our footer according to Netlify's [Open Source Policy](https://www.netlify.com/legal/open-source-policy/).

Add netlify banner to footer

---

client/package.json
client/yarn.lock

This upgrades our typings for react-router so we can access the router hooks like `useHistory()`.

Upgrade typings for react-router.

---

client/package.json
client/src/components/APIDataTypes.ts
client/src/components/BuildingStatsTable.tsx
client/src/components/DetailView.tsx
client/src/components/PropertiesList.tsx
client/src/components/PropertiesMap.tsx
client/src/components/PropertiesSummary.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/util/mapping.ts
client/yarn.lock

This PR adds typescript all remaining pages in the WOW front-end (with the exception of the Address Page and Timeline Pages which will be saved for separate PRs).

Added Typescript to remaining files (except Address Page and Timeline Pages)

---

client/src/components/IndicatorsViz.tsx

This replaces the `any` typing for our ChartJS data to be a `ChartData` instead.

Improve ChartJS typings.

---

client/src/containers/AddressPage.tsx
client/src/state-machine.ts

We're implementing child states so we might as well use a child pull request.

Add timeline, summary child states to "portfolioFound" state

---

.circleci/config.yml
.devcontainer/devcontainer.json
.flake8
dbtool.py
docker_django_management.py
project/settings.py
project/settings_pytest.py
requirements-dev.txt
tests/conftest.py
tests/nycdb_context.py
wow/datautil.py
wow/dbutil.py
wow/tests/test_datautils.py
wow/tests/test_views.py
wow/urls.py
wow/views.py

Add flake8 and clean up python code.

---

client/src/components/APIClient.ts
client/src/state-machine-sample-data.ts
client/src/state-machine.test.ts
client/src/state-machine.ts

This PR adds more tests to our XState Machine so that we now cover all state changes within WoW. For now, fixes #262.

Added more robust State machine tests

---

client/src/containers/BBLPage.tsx

Pass on locale route when redirecting from /bbl route.

---

client/src/components/LegalFooter.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

Changed the footer of WOW to read:
"JustFix, Inc. is a registered 501(c)(3) nonprofit organization."
instead of "JustFix.nyc is a registered 501(c)(3) nonprofit organization."

Updated footer copy

---

client/package.json
client/src/components/PropertiesMap.tsx
client/yarn.lock

Given that our access to our current MapBox styling broke this morning, this is a hotfix that swaps in a new mapbox style from our team MapBox account.

Swap in new mapbox map style and upgrade package

---

client/src/components/SocialShare.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This PR incorporates some content changes and spelling and grammar fixes to our social media share copy, as was revamped in #428.

Grammar edits to social media share copy

---

client/src/components/PropertiesSummary.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

One-sentence copy change to our component that shares the tool via Twitter!

Updated text on Summary Page sample tweet

---

client/package.json
client/src/styles/HomePage.scss
client/yarn.lock

This updates our "react-common" package to pull in new content for the warning banner below the header, notifying people of the extended eviction moratorium.

Update Covid Moratorium banner

---

client/src/components/PropertiesSummary.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This PR updates the generated URL for the [Data Request Form](https://airtable.com/shruDUDHViainzUBB) to auto-fill a new field called `Address` in the AirTable form.

Change structure of Data Request form's URL

---

client/package.json
client/yarn.lock

See https://justfixnyc.medium.com/housing-court-blocks-tenants-from-suing-their-landlords-d7b9e3629a32

Bump react-common package to get new text for banner re: ehpas

---

client/src/components/APIDataTypes.ts
client/src/components/DetailView.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/DetailView.scss

This PR adds a new small section to the Overview Tab that lists out the top 3 311 complaints over the past 3 years and their frequencies.

Add most common 311 complaints to DetailView

---

client/src/styles/DetailView.scss

Make "Learn More" accordion toggle italic on detail view

---

client/src/data/about.en.json
client/src/data/about.es.json
client/src/data/how-to-use.en.json
client/src/data/how-to-use.es.json

This PR updates our screenshots on the How to Use page with new images showing the new features we added in #479, using new content published on Contentful.

Update screenshots on How to Use page

---

client/src/styles/Accordion.scss
client/src/styles/DetailView.scss

This PR fixes an issue where the accordion icon image would disappear once a user clicks on it to open on a mobile device.

Fix Detail View accordion chevron animation on Mobile

---

client/src/components/DetailView.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This small content change updates a bit of the "learn more" blurb in the landlord contact info section to more accurately describe the data provided.

Update small bit of text on DetailView

---

client/src/styles/HomePage.scss

One simple css change that addresses an issue logged in ClubHouse.

Move sample portfolios above the fold on homepage

---

client/src/components/APIClient.ts
client/src/components/Indicators.tsx
client/src/components/IndicatorsTypes.tsx
client/src/components/IndicatorsViz.tsx

This PR refactors a few files to remove duplicate data structures, rename and refactor certain helper functions, and other things to try and clean up the Timeline Tab code a bit...

Refactor Timeline Tab code for clarity and organization

---

client/src/assets/img/Feature_callout_gifs/dropdowns.gif
client/src/assets/img/Feature_callout_gifs/portfolio-tab-redo.gif
client/src/styles/FeatureCalloutWidget.scss

This PR shrinks the file size of some GIFs in the Feature Callout Widget (#391) and also makes a small CSS tweak.

Styling tweaks to Feature Callout Widget

---

portfoliograph/landlord_index.py

We had a problem with the way we were trying to concatenate the two lists of data for the agloglia upload. This PR fixes that bug and adds some type hints for clarity.

fix list concat method for algolia upload

---

client/src/components/PortfolioGraph.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

Minor structural and design changes to the network visualization on the summary tab.

Fix zoom scaling and add reset button to network visualization

---

client/src/components/PropertiesSummary.tsx
client/src/styles/App.scss
client/src/styles/PropertiesMap.scss
client/src/styles/PropertiesSummary.scss
client/src/styles/_vars.scss

This PR makes some minor css styling changes to the top banner and new warning banners on WOWZA.

Adjust colors for all new banners, and make some other spacing adjustments

---

client/src/styles/PropertiesSummary.scss

Add cursor styling to network visualization on Summary tab

---

client/src/components/BigPortfolioWarning.tsx
client/src/components/PortfolioGraph.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

Simple content and styling tweaks.

Content and styling tweaks to the network chart and big portfolio warning on WOWZA

---

client/src/styles/App.scss

Change size and style of WOWZA banner close button

---

client/src/styles/PropertiesSummary.scss

This PR addresses bugs found in QA testing on mobile browsers. 
So far it's just one issue of the graph network viz zoom controls overlapping the big portfolio modal

fix bugs from mobile browsers QA

---

client/src/components/LandlordSearch.tsx

This PR improves on #630 making sure that we only send 1 network request to Algolia for each keystroke inputted in to our landlord name search bar. By consolidating some of our component logic, I was able to achieve a state where we only send one network request on rendering the searchbar, one network request on every input character typed into the searchbar, and don't send any requests on deleting characters or even typing already cached searches.
This PR should leave the accessibility of the search bar unchanged.

Consolidate Landlord Search subcomponents

---

client/src/util/browser.ts
client/src/util/helpers.ts

adds:
- util functions for setting and getting cookie values
- a regex for escaping invalid characters
- const for cookie name
snippet of what it would look like in action with the typeform button: https://github.com/JustFixNYC/who-owns-what/commit/42fb3a87fcca9537fab80b349cddf75356271f9a
[sc-10937]

Add cookie setter/getter utils

---

client/src/containers/App.tsx

moved all the cookie stuff to state so that we could force a rerender when the user submits the survey (in order hide the button without a page reload)! [sc-11209]

Read survey cookie into state, hide button permanently on submit

---

client/.env.local.sample
client/src/components/DeprecationModal.tsx
client/src/containers/App.tsx
client/src/util/browser.ts

getting the component and plumbing set up so we just need to fill in content and localize when we launch
[sc-11497]

Add placeholder legacy deprecation modal hooked up to environment variable and cookie

---

client/src/styles/PortfolioFilters.scss

[fix banner showing through filters on ios](https://github.com/JustFixNYC/who-owns-what/commit/75418897deaecd8f95207ed7898a2b0d8d0fd6c5)
[sc-11777]

fix banner showing through filters on ios

---

client/src/styles/PortfolioFilters.scss

fix padding for mobile view results button

---

client/public/index.html
client/src/components/PortfolioTable.tsx
client/src/index.js
client/src/styles/PortfolioFilters.scss
client/src/styles/PortfolioTable.scss
client/src/styles/_typography.scss
client/src/styles/_vars.scss
client/src/styles/index.scss
client/src/util/helpers.ts

There has been a very noticeable difference in font-weight and letter-spacing across browsers. 
**Chrome**: already pretty much as intended.
**Safari** and **Firefox**: both the font-weight appeared much higher, and the letter spacing was larger. 
I made sure that we have the specific weights specified when loading the font files. I also added `-webkit-font-smoothing: antialiased`, and this solves the weight issue in Safari, but if applied in Chrome it makes it too bold, and does nothing for Firefox. This also didn't help the letter spacing. 
I kept trying to solve this with these sorts of browser-independent fixes, but have just not been able to find something that solves all of them. 
So I've tried to instead use JS to figure out the browser for the user-agent on start up and store that …

Font weight and spacing cross browser consistency

---

client/src/components/PortfolioFilters.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

amending #739 for minor copy change to zip code filter "no records" message after talking more with design

update zip code filter "no records" message

---

client/src/components/DetailView.tsx
client/src/components/PropertiesMap.tsx
client/src/styles/PropertiesMap.scss

Small copy changes in map legend and view portfolio map button

---

client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/components/PortfolioTable.tsx

A few final changes to the text for filters. (Waiting on lingui until we have everything erged into `filters` branch since they cause such merge conflict headaches.)

final filter text updates

---

client/src/containers/App.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

Update the language on the deprecation banner to remove references to any specific dates.

update deprecation banner language

---

client/package.json
client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/components/PropertiesMap.tsx
client/src/styles/PortfolioFilters.scss
client/src/styles/PortfolioTable.scss
client/src/styles/PropertiesMap.scss
client/yarn.lock

Various changes from our second round of QA on portfolio filters map view.
(will change base branch to `portfolio-filters` once `map-filters` is reviewed and merged in)
- [fix wrapping of filter controls for narrow screens](https://github.com/JustFixNYC/who-owns-what/commit/c0d5c420ab4ca439d8e63e8ed63bf85e7df548ce) [sc-12745]
- [increase text contrast for disabled pagination buttons](https://github.com/JustFixNYC/who-owns-what/pull/787/commits/b60a02fe423b1e248a4bfaa093a5d68aec4da515) [sc-12749]
- [resize map when container height changes](https://github.com/JustFixNYC/who-owns-what/pull/787/commits/880633602ba20ebe163806cf372896df77e06842) [sc-12744], [sc-12595]
- this required adding a new package, [react-resize-detector](https://www.npmjs.com/package/react-resize-detector), since there …

Map filter QA revisions

---

client/src/components/PortfolioTable.tsx

fix param name for address change gtm tag

---

client/src/containers/HomePage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

copy edits for example portfolios

---

client/package.json
client/yarn.lock

update shell-quote to ^1.7.2 via resolution to address https://github.com/JustFixNYC/who-owns-what/security/dependabot/90

update shell-quote to ^1.7.2 for dependabot security

---

client/package.json
client/yarn.lock

update loader-utils via resolution to address: https://github.com/JustFixNYC/who-owns-what/security/dependabot/111

update loader-utils via resolution for dependabot security

---

client/package.json
client/yarn.lock

update set-value to ^2.0.1 via resolution for dependabot security: https://github.com/JustFixNYC/who-owns-what/security/dependabot/26

update set-value to ^2.0.1 via resolution for dependabot security

---

client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/util/helpers.ts

when switching over to the new combined HPD complaints and problems data (#832) there were a few new complaint types, so this PR adds them on to the list we have for translations
[sc-13270]

add new compliant types for translation

---

client/src/containers/App.tsx

Remove the "share" button from WOW nav header. 
[sc-13592]

remove "share" from nav

---

client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx
client/src/components/UserSettingField.tsx
client/src/containers/AccountSettingsPage.tsx
client/src/containers/App.tsx
client/src/containers/ForgotPasswordPage.tsx
client/src/containers/ResetPasswordPage.tsx
client/src/containers/UnsubscribePage.tsx
client/src/containers/VerifyEmailPage.tsx
client/src/styles/AccountSettingsPage.scss

Various content changes, updating from the main content spreadsheet
[sc-13967]
Left out some content changes for verification and password reset pages since those also need some other changes
[sc-14144]
[sc-14145]

Content updates

---

client/src/components/UserTypeInput.tsx

content update for user type options

update content changes for user type options

---

client/src/locales/en/messages.po
client/src/locales/es/messages.po

lingui extract

---

client/public/index.html

please excuse how gross the copy paste from the fullstory site looks 🥴

Enable fullstory for email alerts beta testing 

---

client/src/containers/LoginPage.tsx

Reverts JustFixNYC/who-owns-what#922
Trying to get a build on Netlify

Revert "add redirect login -> account when already logged in"

---

client/src/containers/LoginPage.tsx

instead of reverting the revert (😭) just reopening the PR with the same branch

add redirect login -> account when already logged in

---

client/src/components/Login.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

reopening this PR with a cleaner child branch
I hate git, git hates me

Update "email settings" language on standalone page

---

project/settings.py
wow/apiutil.py
wow/forms.py

Just doing this separately to test it out on the branch and ensure everything is still working properly

change back cors setting for signature

---

.circleci/config.yml
project/settings.py

Update settings.py cors origins for renaming `wow-django-dev` -> `wow-django-demo`

wow server rename

---

client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx
client/src/components/UserSettingField.tsx
client/src/containers/AccountSettingsPage.tsx
client/src/containers/UnsubscribePage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

just copy changes for Building Alerts and adding description text to above "Follow Building" button when a user is logged in.

Building Update is now Building Alerts

---

client/src/containers/AccountSettingsPage.tsx
client/src/containers/UnsubscribePage.tsx
client/src/styles/UnsubscribePage.scss
client/src/styles/UserSetting.scss

Adjust type styles and hides "unsubscribe all" button when only 1 entry
[sc-16340]

update styles for manage subscriptions and account settings

---

client/src/components/DistrictMap.tsx

change default map zoom and center on mobile

---

sql/create_districts_geom.sql

remove central park 00083 zipcode from area alerts

---

sql/create_gce_common.sql

Following up on #1028 to further improve our updating of BBLs for CofO records. Now we check all records against PAD using BIN, not just those where the original BBL doesn't appear in PAD. And we also check against PLUTO to make sure we are matching to correct properties with residential units.
Examples:
If you go to this BBLs page on DOB (https://a810-bisweb.nyc.gov/bisweb/PropertyProfileOverviewServlet?boro=4&block=00566&lot=0136) and check the CofOs, there is one recorded in 2010 with BIN=4538508 (https://a810-bisweb.nyc.gov/bisweb/PropertyProfileOverviewServlet?requestid=2&bin=4538508). 
We can find this CofO record in the DOB data (via FOIL for pre-2012) by looking for that BIN, but it is recorded with BBL=4005660037. This BBL 4005660037 doesn't not appear in pluto_latest. So it …

update gce sql to fix c-of-o bbls with pluto match

---

sql/create_gce_common.sql

This rewrite some of the SQL for the Good Cause CofO prep (from recent PR  https://github.com/JustFixNYC/who-owns-what/pull/1030)to speed up the operations by using temporary tables and creating indexes before computationally expensive joins. No changes to the logic

rewrite GCE CofOs prep for speed

---

client/src/containers/AccountSettingsPage.tsx
client/src/containers/DistrictAlertsPage.tsx
client/src/util/helpers.ts

remove zipcode prefix on account settings

---

client/src/components/DistrictMap.tsx

Reflects mocks in [Figma](https://www.figma.com/design/HGchlZuARgCtoo9vQ9MGuR/Area-Alerts-Design?node-id=2206-1281&m=dev)

Area Alerts map colors update
