JustFixNYC/who-owns-what

client/src/components/PropertiesSummary.js
sql/agg_function.sql

Changed formatting on the summary page for buildings that had 0 evictions portfolio-wide. Now actually says "0" and doesn't list a top address.

Evictions count bug fix

---

server/controllers/landlord.js
server/routes.js
server/services/db.js
sql/landlord_contact.sql

This addresses #39 by adding a `landlord_contact` table to Postgres and supplying an accompanying endpoint at `/api/landlord`. It requires a BBL in the querystring as such:
`https://whoownswhat.justfix.nyc/api/landlord?bbl=3012380016`
should return:
```
{
"result": [
{
"housenumber": "654",
"streetname": "PARK PLACE",
"zip": "11216",
"boro": "BROOKLYN",
"registrationid": 352819,
"bbl": "3012380016",
"bin": 3031404,
"businessaddr": "12 SPENCER STREET 4 11205",
"ownername": "MOSES GUTMAN"
}
]
}
```
Some notes:
Fields aren't guaranteed, obviously. See this query:
So we usually have the name but maybe not the business address. We know from WoW development that we're taking a narrow view of the address (i.e. only looking at the `CorporateOwner` field, so there's definitely room for improvement …

adding landlord contact table and endpoint

---

client/src/components/PropertiesSummary.js

In the summary tab, I coded a new ternary operator to generate text for when VPU is "about the same" as the average.

created "about the same" case when comparing VPU to average

---

client/src/components/PropertiesMap.js
client/src/styles/PropertiesMap.scss
client/src/util/mapping.js

This was a tricky one. Apparently there is little or no accounting for this - I looked through [react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md) and tried some of the event handlers (`onWebGlContextLost`, `onError`?) but they didn't seem to affect anything.
So in the meantime I threw in some code that detects if the browser has WebGL or not (see `MapHelpers`), and throws up a terrible error message and doesn't allow the user to use the map at all:
You can disable WebGL/hardware acceleration on Chrome in Settings > Advanced Settings > Use hardware acceleration when available:
@toolness @sraby interested to hear your thoughts! Specifically it would be good to know if we can find a way to degrade this in a better fashion so a version of the map could …

Adds handling for browsers where WebGL is disabled or unavailable

---

client/src/components/DetailView.js
client/src/containers/App.js
client/src/containers/BBLPage.js
client/src/styles/LegalFooter.scss

(mainly out of convenience for myself) I added a route with one single url parameter for a full non-delimited bbl, and a small IF statement to BBLPage to slice out each boro, block, and lot from that input. 
So, for example, the url `.../bbl/2031840066` should work sans backslashes!

url support for searching via full bbl

---

server/express.js
server/services/mailchimp.js

While working on #92, I ran into a problem where the API server on port 3001 silently crashed with a 0 exit code (0 meaning "I finished without crashing").  I eventually found out that it was silently crashing because Rollbar installed an uncaught exception handler that was exiting with a 0 exit code (which still strikes me as extremely odd).
This allowed me to see the actual exception that was causing the crash, which was due to my `MAILCHIMP_API_KEY` environment variable being undefined. This environment variable isn't actually documented anywhere, so there was no way for me to know that it even needed to be defined. I modified the code to default the environment variable to the empty string instead of `undefined`, thereby preventing the crash; I also added a logging statement that …

Fix silent server crashes in development, and make MAILCHIMP_API_KEY optional.

---

dbtool.py
requirements.txt
who-owns-what.yml

We need to be able to load/update the WoW database from our containerized DB updater at https://github.com/JustFixNYC/nycdb-k8s-loader/pull/22.  One simple way to do this is by putting all our database configuration into a YAML file, similar to what NYCDB is already doing.
This PR moves the names of all the NYCDB dataset dependencies and the SQL filenames into a new `who-owns-what.yml` file.  It also makes the following changes:
* We no longer load the `pluto_17v1` dataset; it seems this was entirely superseded by `pluto_18v1`, although I should check with @sraby to make sure this is OK.
* The `--update` option for `dbtool.py builddb` now wipes _all_ nycdb data instead of just a subset of tables. This simplified the structure of the YAML and seems OK since nycdb-k8s-loader will now be …

Move WoW db config out to a YAML file.

---

client/src/components/PropertiesMap.js
client/src/containers/AddressPage.js

I refactored PropertiesMap component so that the map pans anytime the detail address prop changes. I suspect this isn't the best way to do this? Open to discussion @romeboards @toolness :) 
Still to do:

Bug fix: map now pans when new address selected from list view

---

client/src/containers/HomePage.js

I found an explanation in this SO post:
https://stackoverflow.com/questions/48731207/react-router-dom-and-redirect-not-being-added-to-history
That post references this part in the router docs:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Redirect.md#push-bool
When redirecting to the search results, nothing was being added to the history, as if the user had never left the initial home page. When clicking the back button, the browser would have to go back to a different page unless the user had clicked any other links on the WOW page.

Resolves issue #93

---

client/src/components/PropertiesSummary.js

- Calculating on recent data, average hpd violations per registered unit goes up to 0.9 :/ I updated a constant to change this number in summary tab
- Fixed a bug where certain fields of type `bigint` from the agg data table were actually of type text when called within the Property Summary component (@toolness I actually noticed this bug after merging #95, where you swapped out `==` for `===`)  I used `parseInt` to convert the non-int values to int so we can use them in comparison statements.
@toolness and @romeboards, is it worrying that there is a type mismatch between data from our agg table and what actually gets called within the Property Summary component?

Bug fix + updated avg. violations per unit count for Property Summary view

---

client/package.json
client/src/react-app-env.d.ts
client/src/util/browser.ts
client/tsconfig.json
client/yarn.lock

This adds TypeScript support to the client, a prerequisite for sharing code from https://github.com/JustFixNYC/tenants2/pull/442 to make progress on #53, by following the [Adding TypeScript](https://facebook.github.io/create-react-app/docs/adding-typescript) instructions for CRA.
It also almost-trivially converts `browser.js` to `browser.ts` to show that the TS support works.
* I've manually verified that inserting a type error to `browser.ts` causes `yarn build` (which is run on CircleCI) to fail, so we will be alerted whenever type safety is violated.
* I've manually verified that everything still works on IE11.  I've also added some ES6-specific syntax to `browser.ts`, like arrow functions and default arguments, and verified that everything still works on IE11 (i.e., that the TS is …

Add TypeScript support to client, convert browser.js to ts

---

client/src/components/IndicatorsViz.js

This avoids the use of the deprecated [`componentWillReceiveProps()`](https://reactjs.org/docs/react-component.html) by creating a wrapper component responsible for passing the correct props, including `shouldRedraw` and `animationTime`, on to the actual implementation.

Avoid use of componentWillReceiveProps() in IndicatorsViz component

---

client/src/styles/PropertiesMap.scss

seems like react-mapbox-gl doesn't support custom positioning for the attribution control... so in the meantime I'm going to place the standard control above the map legend ( fixes #145 )

placed map attribution control above legend

---

client/src/components/DetailView.js

I considered limiting the HPD Violations count, but since there are some violations still open that were issued in the 60s, 70s (oof!), we'd then have cases where there were more "open violations" than "total violations" listed for a building. I thought that would be confusing and misleading to users, so instead I'm keeping to full total count.

fixed inaccurate tooltip for Total HPD Violations

---

tests/test_sql.py

So this adds a test to make sure that `get_assoc_addrs_from_bbl` links buildings whose HPD registration contacts have similar names, but it also reveals some funky things.  Most notably, the portfolio generation is very specific to a BBL and `get_assoc_addrs_from_bbl` isn't transitive (I had to remove the bidirectionality test because of this).  This is (at the very least) because the name matching is done based on the name(s) of the HPD contacts of the building that starts the search.  See the test code for more details.

Add SQL test for fuzzy string matching.

---

client/package.json
client/src/components/AddressToolbar.tsx
client/src/components/Modal.tsx
client/src/globals.d.ts
client/yarn.lock

This converts the `<AddressToolbar>` and `<Modal>` components to TypeScript.
The main benefit is that props for the components are now semi-documented--I say "semi" because I haven't added any comments documenting what each property is for, because I'm not very familiar with the code, but at least the name and type of the props are documented now.  Although even the types might be slightly inaccurate--since the consumers of these components haven't been converted yet, I'm just making educated guesses about the types, but we can revise them going forward.
Anyways, it's a start at least.  I think that as we make the types more explicit, it will become easier for folks to understand the code, and it should also uncover potential type errors, like our buddy `Cannot read property 'bbl' of …

Convert AddressToolbar and Modal components to TypeScript

---

Dockerfile

For some bizarre reason, Labiba's computer (and possibly anyone who now tries using our Dockerfile from a freshly-installed Docker install, I'm not sure) was prioritizing Debian's default nodejs package over nodesource's, which meant that the wrong version of node was being installed _and_ npm wasn't being installed at all.
This ensures that node is installed from the correct package using the technique described at https://github.com/nodejs/help/issues/554#issuecomment-429633801.

Ensure nodeJS is installed via nodesource.

---

client/package.json
client/yarn.lock

This uses the [cross-env](https://www.npmjs.com/package/cross-env) module to set `NODE_PATH`, which makes it possible to run the front-end on Windows.

Use cross-env to set NODE_PATH.

---

server/express.js

This should fix #169 by making the server return 404 for any paths that miss express' `static` middleware and look like static files.

Return 404 for nonexistent static files

---

client/package.json
client/public/index.html
client/src/components/DetailView.js
client/src/components/StreetView.tsx
client/src/globals.d.ts
client/yarn.lock

Fixes #197.
It also fixes a bug whereby our `<script>` tag that loaded the Google Maps API was hard-coded to use our current API key, rather than pulling from `process.env.REACT_APP_STREETVIEW_API_KEY`.
It also explicitly makes us use v3 of the Google Maps API (I think we were using v1 before but I'm not sure).

Upgrade react-google-maps to 9.4.5

---

client/src/components/DetailView.js
client/src/components/LazyLoadWhenVisible.tsx

This fixes the issue mentioned in https://github.com/JustFixNYC/who-owns-what/pull/200#issuecomment-561656193 whereby we actually fully render _two_ street view widgets per detail page--one for the mobile view and one for the desktop view.
This uses an [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to only instantiate the widget if we know it's going to be visible.
However, Intersection Observer is a newer browser API that's not available on all browsers, such as IE11.  If it's not available, we simply fall back to the old behavior of just rendering the street view widget.  Since a small minority of browsers won't have the API, I think this will still be a net win.

Only create StreetView when we know it's visible.

---

.circleci/config.yml
client/package.json
client/src/components/AddressSearch.test.tsx

Oops, while `yarn build` type-checks all production code, it doesn't type-check tests and other things, so we actually had some test code that didn't type-check properly.  This adds a `yarn typecheck' command and runs it during CI, and also fixes the type errors in the test code.

Add 'yarn typecheck' and run it during CI.

---

client/src/i18n-base.test.ts
client/src/i18n-base.ts
client/src/i18n.test.tsx
client/src/i18n.tsx

This factors out a separate TypeScript-only (no TSX/React) module called `i18n-base` that has no dependencies, does not assume a browser runtime, and can be used by node scripts with minimal transpiler configurations (e.g. #203).
It also renames the `Locale` typing to `SupportedLocale`, as this is more accurate and also doesn't conflict with other third-party type names (in particular, Contentful's packages define their own `Locale` type).

Factor out i18n-base.ts, rename Locale to SupportedLocale

---

client/src/util/helpers.ts

Added functionality so when the local env var `REACT_APP_DEMO_SITE` is set to `1`, all outbound "Take Action" links to DDO now go to the demo tenant platform

refactored DDO links so they go to .demo on demo site

---

client/src/components/DetailView.js
client/src/components/EvictionsSummary.tsx
client/src/components/PropertiesList.tsx
client/src/containers/NychaPage.js
client/src/data/nycha_bbls.json
client/src/locales/en/messages.po
client/src/locales/es/messages.po
sql/create_bldgs_table.sql
sql/nycha_stats.sql

I updated our wow buildings sql to include the new 2019 evictions data we have, changed relevant text throughout the site to match, and also updated our nycha data with new eviction and res unit counts.

Upgrade evictions data to 2019

---

README.md

#209 was a bit challenging because the process of updating WoW's data wasn't very well-documented!  This attempts to add a bit of documentation about the whole shebang so it's not as hard next time around.

Add docs about updating data

---

server/controllers/address.js

This fix allows @0xStarcat to access the dap api in testing on their local machine.

Set the 'Access-Control-Allow-Origin' header on the dap api endpoint to *

---

client/src/components/AddressToolbar.tsx
client/src/components/DetailView.js
client/src/components/Indicators.js
client/src/util/helpers.test.ts
client/src/util/helpers.ts

Seems that [HPD's Online Portal](https://hpdonline.hpdnyc.org/HPDonline/select_application.aspx) doesn't like when streetname prefixes are spelled out (when E 21st is 'EAST 21ST'). This PR adds a helper function that tries to format these street prefixes in the preferred way to limit broken links to HPD Building Profile pages.

Added new helper function to correctly format street names for outbound HPD links

---

client/src/components/DetailView.js
client/src/components/Indicators.js
client/src/components/PropertiesList.tsx
client/src/components/SocialShare.tsx
client/src/containers/AddressPage.js
client/src/containers/App.js
client/src/styles/Indicators.scss
client/src/styles/_tabs.scss

This PR improved the accessibility and usability of Who Owns What by assigning a specific url path to each of the four tabs we include on the address page. Now users can tab through links to navigate between these pages as well as share each individual URL allowing another user to have a direct link to that page. 
Specifically, this PR:

Add urls and focus styles to address page tabs

---

client/src/components/AddressToolbar.tsx
client/src/components/DetailView.js
client/src/components/Indicators.js
client/src/components/IndicatorsViz.js
client/src/components/OwnersTable.tsx
client/src/components/PropertiesList.tsx
client/src/containers/NotRegisteredPage.js
client/src/containers/NychaPage.js
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/util/helpers.test.ts
client/src/util/helpers.ts

This PR implements various i18n tweaks that address some mission translations and other bugs detected during a QA session, such as:
1. Adding in missing i18n infrastructure (such as with the tooltips on the detail view)
2. Consolidating our choices of language to make wording more consistent, and thus reduce work for a translator
3. Internationalized dates and month abbreviations on the overview and timeline tabs

I18n tweaks

---

client/src/styles/DetailView.scss
package.json

This PR adds `yarn prettier:check` to our build command to throw an error if our code isn't formatted via prettier.

Made prettier formatting required for build

---

client/src/components/Indicators.js
client/src/containers/AddressPage.js
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/AddressPage.scss

This PR adds one missing <Trans> tag which hopefully marks an end to internationalization. It also fixes an issue with the `detailAddr` prop disappearing on mobile as well as loading pages not taking up the full viewport height.

Added missing internationalization tag and updated styling

---

client/src/components/APIClient.ts
client/src/components/Indicators.js
client/src/components/PropertiesList.tsx
client/src/data/about.es.json
client/src/data/how-it-works.en.json
client/src/data/how-it-works.es.json
client/src/data/how-to-use.es.json
client/src/locales/en/messages.po
client/src/locales/es/messages.po
server/controllers/address.js
server/routes.js
server/services/db.js

This PR adds data on buildings' last sale in ACRIS, using the new `wow_bldgs` structure implemented in #246. Specifically, this PR:

Add "Last Sale" data to WOW Portfolio page

---

client/src/components/PropertiesList.tsx

This PR makes sure that any Cell render function in our PropertiesList table component always returns something.

Fixed bug where React Table cell doesn't return anything

---

client/.env.local.sample
client/src/i18n.tsx

This PR removes our feature flag that determined whether to show our public-facing language toggle and redirection.

Remove the public-facing i18n feature flag

---

client/src/components/DetailView.js
client/src/components/PropertiesList.tsx
client/src/containers/AddressPage.js
client/src/data/how-to-use.es.json
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This PR updated the Spanish version of our "How to use" page to include translations of HPD contact names, and also adds an internationalized "Last sold" note to the detail view.

Add new spanish elements

---

client/public/index.html
client/src/components/GoogleTagManager.tsx
client/src/containers/App.js

This adds a `<GoogleTagManager>` component, which does the following:
```js
/**
* Google Tag Manager reports the title of the landing page when it
* initializes, but because we only render the <title> on the client-side
* via React, we need to wait until it's rendered before we initialize
* GTM.
*
* This inserts the GTM script tag on mount, which is assumed to also
* be when the <title> tag should be set. This should ensure that
* GTM reports the correct landing page title.
*/
```

Initialize GTM in React.

---

client/src/components/Page.tsx
client/src/containers/App.js

This PR attempts to fix the issue that made our google analytics disabled on Who Owns What— it moves the GTM tag to be within the head and not the body of each page.

moved GTM tag to inside React Helmet component

---

.env.sample
client/.env.local.sample
client/src/components/APIClient.ts
client/src/components/Subscribe.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
server/controllers/subscribe.js
server/services/mailchimp.js

This PR replaces our current API for Mailchimp email signups and instead uses the [new API endpoint implemented in the Tenant Platform](https://github.com/JustFixNYC/tenants2/pull/1549/files)! It makes a note that the current server functions to handle Mailchimp signups are deprecated (see #289).

Refactored Mailchimp sign-ups to use new external API

---

.env.sample
README.md
docker-compose.yml

This PR configures our `docker-compose.yml` file to reference the `DATABASE_URL` env variable when constructing the virtual environment, which allows the developer to dynamically override the database reference if they want to. It also updates our `env.sample` to include the correct default value for this env variable if the user follows the basic Docker instructions on the ReadMe.

Utilize `DATABASE_URL` env variable in docker compose

---

client/package.json
client/src/components/APIClient.ts
client/src/components/APIDataTypes.ts
client/src/components/AddressSearch.tsx
client/src/containers/AddressPage.js
client/src/containers/BBLPage.tsx
client/src/containers/HomePage.tsx
prettier.config.js

This PR fixes #258 by adding type definitions to all the data objects we receive from API calls to the database. It adds a new file called `APIDataTypes.ts` which includes these new typings as well as some pre-existing type infrastructure corresponding to data we input into these API calls. 
The typings were made based on the expected responses from these APIs (in reference to the data in nycdb they retrieve). I made sure to leave a comment next to any type that doesn't match up with how the front-end will interpret it. I aim to deal with these cases when we address #297 .

Add typescript definitions to all data-related API responses

---

.devcontainer/devcontainer.json

This adds a `.devcontainer` folder for VSCode Remote Container Development.  It's largely based off https://github.com/JustFixNYC/tenants2/pull/1583.
Currently eslint integration doesn't actually seem to work, probably because of this whole doggone two `package.json`s thing.  Sigh.  CRA actually disincentivizes writing a backend in JS, since implementing a backend in a different language would only result in a single `package.json`.

Add a .devcontainer setup for VSCode.

---

client/src/components/IndicatorsViz.js
client/src/util/helpers.ts

This PR fixes a bug where the abbreviation of months on the timeline tab would show up as invalid values— specifically when viewing the data by quarters on Safari or Firefox.

Fix bug on indicator vis tooltip for "quarter" view

---

client/src/components/LegalFooter.tsx

This quick fix fixes the bounding box for the netlify banner in the footer.

Hot fix: include wrapping div for netlify banner

---

client/src/styles/HomePage.scss

This quick PR fixes a styling bug on our COVID-19 banner on the homepage— now, the hyperlink text is allowed to wrap to two lines, avoiding spacing awkwardness.

Allow wrapping on covid banner link text

---

dbtool.py
tests/nycdb_context.py
who-owns-what.yml
wow/tests/conftest.py

This fixes #291 by adding a new `api_dependencies` array to `who-owns-what.yml` that declares NYCDB datasets that aren't needed to run WoW's SQL scripts (the ones that define functions and materialized views, etc) but which _are_ needed by the API server.  It also modifies `dbtool.py` to load these dependencies too.

Add api_dependencies array to who-owns-what.yml.

---

requirements.txt
wow/tests/test_views.py
wow/views.py

This upgrades us to Django 3.0 and adds more tests.  This fixes #313.
(The main reason for upgrading to Django 3 is because of its support for the `raise_request_exception` argument to the Django test client, which makes it easier for us to test our HTTP 500 errors.)

Upgrade to Django 3.0 and add more tests.

---

README.md
client/package.json

This PR makes node version 12 or higher a requirement in our `package.json` file. It also updates the ReadMe to reflect this requirement. Fixes #100!

Specify node version 12 or higher in package.json

---

client/src/components/APIDataTypes.ts
wow/datautil.py
wow/tests/test_datautils.py
wow/views.py

This PR fixes #297 by adding explicit type casts in python to any API response data that isn't in the right type that the front end would interpret it to be in. At some point, we should determine how we can log explicit errors for when these typecasting methods totally fail (for example, if we ever tried to cast "BOOP" into an integer)

Add explicit typecasts to any API data we need to alter for the front end

---

client/src/containers/App.js
client/src/containers/VersionUpgrader.tsx

This adds functionality that regularly checks to see if a new version is available, and if so, upgrades the user when they next click on a link, submit a form, or perform any other kind of page navigation.
The one annoying thing with this solution is that it actually reloads _after_ the page transition, which could be a bit jarring for the user, as they'll see the new page but then see it immediately reload.  Ideally we'd convince React Router to make all page transitions "hard" once we know an upgrade is available, but there doesn't seem to be a way to do this.
One nice thing about Netlify's deploy previews is that they can be used to test out this functionality: if you load the deploy preview, and then push a commit to this PR, you should eventually see the following message in the …

Upgrade version if needed when user navigates to a new page.

---

client/src/components/APIDataTypes.ts
wow/views.py

While WoW never seems to ping the `/api/aggregate` endpoint for BBLs that have no HPD registration, DAP does (albeit at the synonymous `/api/dap-aggregate` endpoint), and it sometimes asks about buildings that apparently either have no PLUTO data, or for which PLUTO reports the building's age as being `NULL`.  Regardless, the value our NYCDB returns is `NULL`, which our typecasting code introduced in #326 barfs on, so this fixes it.
The offending BBLs are very small buildings so I'm not comfortable posting the examples here, but they can be seen on Rollbar at https://rollbar.com/justfix-nyc/who-owns-what/items/1957/.

Allow for age to be null in aggregate endpoint

---

client/package.json
netlify.toml

Looking at Rollbar errors for the latest front-end version made me realize that there were arrow functions in our JS bundles.  Upon further inspection, I realized our `browserslist` specifies `not ie <= 11`, yet our `index.js` imports both `react-app-polyfill/ie11` and `babel-polyfill`.  These contradictory lines were actually all introduced in the same PR, #99, which is very odd.
I think the reason we might not have seen this strange behavior when writing that PR is because apparently [changing `browserslist` requires deleting `node_modules/.cache`][1].  So it's possible that during development, we never truly saw the results of our actions!  (Needless to say, I spent a lot of time in confusion after making this PR's simple code change, until I discovered the root cause.)
This means that …

Actually support IE 11 and non-ES6 browsers

---

client/src/components/APIClient.ts
client/src/containers/AddressPage.js

This fixes #329 by factoring out a new function called `APIClient.searchForAddressWithGeosearch()` which first uses the GeoSearch API (properly) to get the BBL for an address, and then passes the BBL on to the WoW API to get portfolio information.
It also modifies `APIClient.searchForAddress()` to use this function if it's not given a BBL, which fixes #317.

Factor out APIClient.searchForAddressWithGeosearch().

---

dbtool.py
project/settings_pytest.py
requirements-dev.txt
wow/tests/test_views.py

This upgrades mypy and also fixes a [yaml deprecation warning](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).  It also pins pyproj to 2.1.3 (the minimum supported by nycdb) to squelch some deprecation warnings (see https://github.com/nycdb/nycdb/issues/134).

Upgrade mypy to 0.782, pin pyproj to 2.1.3.

---

client/src/components/EvictionsSummary.tsx
client/src/components/OwnersTable.tsx
client/src/components/RentstabSummary.tsx
client/src/components/SocialShare.tsx
client/src/components/ViolationsSummary.tsx
client/src/util/helpers.test.ts
client/src/util/helpers.ts

This PR updates various components that utilize API Data to now reference types from APIDataTypes.ts instead. It also removes the `MaybeStringyNumber` type and the `CoerceToInt` helper function as those are no longer needed in our new world of strongly typed data inputs!! 
Fixes #348.

Coalesce our pre-existing data-related type definitions with the new ones

---

client/src/locales/es/messages.po

This HotFix PR adds back a translation on the Summary Tab that got overwritten during our refactoring in #362.

Added back ES translation that got overwritten

---

client/package.json
client/src/components/APIClient.ts
client/src/components/AddressSearch.tsx
client/src/components/Indicators.tsx
client/src/components/IndicatorsTypes.tsx
client/src/components/IndicatorsViz.tsx
client/src/components/PropertiesList.tsx
client/src/components/PropertiesMap.tsx
client/src/components/PropertiesSummary.tsx
client/src/containers/AddressPage.tsx
client/src/containers/BBLPage.tsx
client/src/containers/HomePage.tsx
client/src/containers/NotFoundPage.tsx
client/src/containers/NotRegisteredPage.tsx
client/src/containers/NychaPage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/routes.tsx
client/src/setupTests.js
client/src/state-machine.test.ts
client/src/state-machine.ts
client/src/tests/test-util.tsx
client/src/util/helpers.ts
client/yarn.lock

This PR moves our entire front-end codebase towards managing major API requests and state management with [XState](https://xstate.js.org/docs/). Now, we handle all major transitions between different "states" of the tool through a global `state-machine.ts` implementation. 
Fixes #264! 
Still to do: 
Once merged:

Add Xstate as our handler of all API data and state management

---

client/src/containers/BBLPage.test.tsx
client/src/containers/BBLPage.tsx
client/src/setupTests.js

This PR adds tests for our BBLPage component, which, for now, just consists of one test that checks whether we are appropriately reformatting the URL params that the component receives. This specific test makes sure that both url formats for our BBL direct links work— `/bbl/4015640058` and `/bbl/4/1564/58`, for example.

Added test for the bbl page params formatting function

---

client/src/components/APIClient.ts
client/src/state-machine.test.ts
client/src/state-machine.ts
client/src/util/helpers.test.ts
client/src/util/helpers.ts

This PR consolidates some duplicate helpers (like `splitBBL`), moves some function declarations around so that helpers.ts only includes globally-relevant helper functions, and adds full test coverage for all.

Cleaned up our helper functions and added full test coverage

---

client/src/containers/BBLPage.tsx
client/src/containers/DevPage.tsx
client/src/routes.tsx

This adds a page at `/dev/` that contains a panoply of addresses (cribbed from the [tenants2 wiki](https://github.com/JustFixNYC/tenants2/wiki/Useful-NYC-addresses)).
It also changes `history.push()` in the BBL endpoint to `history.replace()` as otherwise the user's back button breaks.

Add /dev/ page with developer docs, manual tests.

---

client/src/containers/BBLPage.test.tsx
client/src/containers/BBLPage.tsx

This PR adds logic to our BBLPage that renders the "No Address Found" page if the bbl passed from the url parameters is not 10 characters long or is not solely digits.  This should fix #338 in that we no longer should see that error as something that's our fault.

Added check for bbl format on BBLPage.tsx

---

client/src/components/APIClient.ts
client/src/components/Subscribe.tsx
client/src/containers/BBLPage.tsx
client/src/error-reporting.test.tsx
client/src/error-reporting.ts
client/src/routes.tsx
client/src/setupTests.js
client/src/state-machine.ts
client/src/util/helpers.ts

This adds a new module called `error-reporting.ts` which introduces a new function, `reportError()`, that we should use to report errors from now on (rather than calling `window.Rollbar.error()` or `console.error()` directly).  In doing so, it decouples us a bit more from Rollbar.
It also fixes #378, in part by adding a new `NetworkError` exception (it looks like the default errors raised by `fetch` are just `TypeError` which is awfully ambiguous).  A `NetworkError` has a `shouldReport` property which defaults to false, but it can be changed to true if it's something that we'd like to know about.  For example, we don't want to report HTTP 500 errors from our own API servers because we know they will report the errors to us from their end, and with more helpful contextual information.  But …

Improve error handling.

---

client/src/containers/HomePage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This PR updates the text on our Eviction Moratorium banner on the homepage. It specifically removes a mention of any date so that the messaging is more "evergreen" and doesn't need to be updated every time the Moratorium is extended.

Updated copy for moratorium banner and reran lingui extract

---

client/src/components/DetailView.tsx
client/src/components/Indicators.tsx
client/src/components/IndicatorsTypes.tsx
client/src/components/PropertiesList.tsx
client/src/components/SocialShare.tsx
client/src/containers/AddressPage.tsx
client/src/containers/App.tsx
client/src/containers/BBLPage.tsx
client/src/containers/NotFoundPage.tsx
client/src/routes.test.tsx
client/src/routes.tsx

This factors out a new function called `createAddressPageRoutes()` which cleans up the creation of links to sub-pages of the address page, making them more type-safe and DRY.
It also moves the `WhoOwnsWhatRoutes` component into `App.tsx` to avoid circular imports.  This is also more ideal: `routes.tsx` should be only concerned with routing pathnames, rather than what routes map to what components, making it as dependency-free as possible so that anything that imports it doesn't also end up importing every module in the codebase (this will come in handy with Jest's detection of dependent tests, as well as if/when we decide to do code splitting).
Unrelatedly, it also removes the double quotes around the word "owns" in the Twitter sharing message, because that was really weird.  (This does …

Factor out createAddressPageRoutes() and add a 404 page.

---

client/src/components/PropertiesMap.tsx

Fixes #191.
When loading the address page, the following annoying warning is always logged:
> This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.
The actual page doesn't seem to have any visual problems, though... Still, the warning is annoying and according to https://github.com/mapbox/mapbox-gl-js/issues/5785 we need to import the CSS in our code, which this commit does, and the warning goes away.  I just hope it's not adding unnecessary bloat to our page weight...

Include Mapbox GL CSS.

---

client/src/state-machine.test.ts
client/src/state-machine.ts

Apparently there are some addresses that map to actual BBLs in GeoSearch and represent real buildings, but which PLUTO doesn't have entries for.
An example of one (at the time of this writing) is 77 Park Place in Manhattan, which [exists according to StreetEasy](https://streeteasy.com/building/the-griffon) and has BBL 1008940201 according to NYC GeoSearch, but which apparently PLUTO 19v2 has no information about.  Because of this, the API request for building info returns an empty array, which the `NotRegisteredPage` component chokes on (currently with an exception of `Cannot get property 'charAt' of undefined or null`).
(Interestingly [ZoLa chokes on this address as well](https://zola.planning.nyc.gov/l/lot/1/894/201).)
I'm not sure what the best fix for this is, but this PR basically …

Deal semi-gracefully with BBLs not in PLUTO.

---

client/src/components/Indicators.tsx
client/src/components/NetworkErrorMessage.tsx
client/src/components/PropertiesSummary.tsx
client/src/containers/AddressPage.tsx

Fixes #384. Fixes #318. Also factors out a `<NetworkErrorMessage>` component to make things more DRY.

Add a network error page for AddressPage.

---

client/src/components/APIDataTypes.ts
client/src/state-machine.test.ts
wow/tests/test_views.py
wow/views.py

This PR fixes #379 by removing an antiquated and useless piece of our GeoSearch response data.

remove all instances of geosupportReturnCode inside GeoSearchData

---

client/package.json
client/src/containers/HomePage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/HomePage.scss
client/yarn.lock

This PR makes use of the new react-common package out of our @JustFixNYC monorepo on npm- we now pull the content for the COVID Eviction Moratorium banner from there.

Replaced COVID banner with component from monorepo

---

client/public/_redirects
client/public/not-found.html

It seems #169 re-emerged when we moved the front-end over to Netlify, because Netlify is currently returning the WoW index page with a status of 200 for _every_ URL, including static assets.  This modifies our `_redirects` to actually return 404 for such files, which should hopefully result in less spurious syntax errors coming from Rollbar.

Return HTTP 404 for nonexistent files under /static/.

---

client/src/components/PropertiesSummary.tsx

This PR adds in some spaces into the "full address" parameter we include in the URL to our Data Request Google Form. It fixes an issue where addresses would show up on the form improperly formatted, like `921EAST 145TH STREET,BRONX`.

Added spaces back into the Data Request URL

---

client/src/components/PropertiesMap.tsx
client/src/util/mapping.test.ts
client/src/util/mapping.ts

This fixes #405.  The problem arises when a portfolio only contains addresses with `null` latitude/longitude information, such as (at the time of this writing) "3070 Brighton 14th Street, Brooklyn".  This causes our bounding box calculation algorithm to return an _infinite_ bounding box which Mapbox really dislikes.
This resolves the situation by setting the default map bounds to be the NYC area instead of an infinite box.  I'm not sure if it's actually the most user-friendly fix since the user may be confused and wondering where the map pins are, but at least the entire page doesn't crash and the user can see other information about the properties?

Support property maps with no pins.

---

client/src/components/DetailView.tsx
client/src/components/IndicatorsTypes.tsx
client/src/components/IndicatorsViz.tsx
client/src/components/PropertiesList.tsx
client/src/components/PropertiesMap.tsx
client/src/components/PropertiesSummary.tsx
client/src/containers/AddressPage.tsx
client/src/containers/HomePage.tsx
client/src/containers/NotRegisteredPage.tsx
client/src/containers/NychaPage.tsx
client/src/state-machine.ts

This PR fixes #409 and #410— namely, it refactors the DetailView component like we did other AddressPage child components so we don't have to pass it the addr and addrs props down from its parent. It also introduces a new handler called `onOpenDetail` that makes sure to bring in the DetailView on mobile when a user mounts the address page for the first time.

Clean up DetailView component 

---

tests/nycdb_context.py
who-owns-what.yml

It's super confusing to add new NYCDB dataset dependencies to WoW because of how our tests work, so this moves the mention of any CSVs that we need to directly copy over into a new `extra_nycdb_test_data` entry in the `who-owns-what.yml` file.  Now whenever we add a new nycdb dataset dependency, hopefully we can just specify any additional CSVs in this area so tests know how to scaffold the dataset for tests.

Add 'extra_nycdb_test_data' section to YML config.

---

client/package.json
client/yarn.lock

This is a routine update of our `react-common` package from our justfix-ts monorepo to reflect new changes to our COVID-19 product banner.

Update COVID-19 banner

---

client/package.json
client/yarn.lock

This simple PR upgrades our react-common package so that we can update the content on our COVID moratorium banner component at the top of the landing page.

Upgrade react-common package to 0.0.4

---

client/src/i18n.test.tsx
client/src/i18n.tsx

This PR fixes a bug where WOW would redirect paths without a trailing slash incorrectly. For example, any url ending in `/en` or `/en?utm....` would be interpreted as not having a locale defined, and then get redirected to `/en/en...` which was not a correct route. We reconfigured our `parseLocale...` code to recognize locales in the pathname even if there is no trailing slash present.

Remove trailing slash from parseLocale function

---

client/.env.local.sample
client/src/containers/App.tsx

So, I noticed this morning that Who Owns What was showing the warning about using an "older version of Safari" on my newly updated Chrome browser. 
I then checked the CSS logic for how this banner shows up and while I didn't have the time to fully investigate, it did seem a bit thrown together and perhaps not relevant to a new updates of modern browsers like Chrome. 
Of course, we should look in to this more in depth but for now, I'm adding a feature flag so we can disable this banner altogether while we investigate the issue.

Add feature flag to disable old browser warning banner

---

client/src/components/DetailView.tsx
client/src/components/EngagementPanel.tsx
client/src/components/PropertiesSummary.tsx
client/src/components/SocialShare.tsx
client/src/containers/AboutPage.tsx
client/src/containers/HowToUsePage.tsx
client/src/containers/Methodology.tsx
client/src/containers/NotRegisteredPage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/react-social.d.ts

This PR adds new content to our SocialShare component— specifically the content that gets pre-filled when a user tries to share the tool via email or twitter from the homepage, Overview tab, Summary tab, or elsewhere.

Update content in our SocialShare component

---

client/src/components/DetailView.tsx
client/src/components/PropertiesSummary.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This PR is a quick follow-up to #428 that removes some periods which were interfering with outbound links in pre-filled email body text.

Removed periods from Social Share email body text

---

client/src/containers/AddressPage.tsx

This PR fixes an important but hard to reproduce bug where Mobile users couldn't use the Overview tab if they were to search ANOTHER address after their initial search. What was happening is that the "detailMobileSlide" state on the AddressPage component was pre-configured, so when the user returned to the AddressPage after searching a second address, it was not properly retriggering the opening of the DetailView slide and so users could only view the property map and not see any details. This PR fixes this issue by making sure the DetailView slide is "closed" every time a new address search is conducted.

Close DetailView on mobile for every new address search

---

requirements.txt

Previously, who-owns-what tests were failing with the error "AttributeError: module 'psycopg2.errors' has no attribute 'UndefinedTable'".
They were failing because they used syntax that only works if you have psycopg2 v 2.8.6 installed, but that wasn't explicitly stated as a dependency. The computer the tests were written on 8 months ago actually had 2.8.6 installed instead of the expected 2.7.7. It had 2.8.6 installed because nycdb's requirements.txt asks for nycdb >= 2.7, and whenever WOW's requirements-dev.txt gets loaded, it fetches the latest version of psycopg2.
We thought we had pinned psycopg2 to version 2.7.7, but instead we had psycopg2-binary pinned to 2.7.7, which was ineffective at preventing arbitrary library updates from its dependencies (i.e. nycdb).
This makes it so we're …

Stop using psycopg2-binary and use psycopg2 with a higher version.

---

client/src/components/PropertiesSummary.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

Our new WOW Data Request form is built on AirTable and is available in [English](https://airtable.com/shruDUDHViainzUBB) and in [Spanish](https://airtable.com/shrQudDbhUVz5J83u)! This PR updates our outbound link on the Summary tab with the new form in its full i18n splendor.

Add new internationalized AirTable Data Request form to Summary tab

---

sql/create_bldgs_table.sql
tests/factories/hpd_complaint_problems.py
tests/factories/hpd_complaints.py
tests/test_sql.py
who-owns-what.yml

This adds three new columns to the `wow_bldgs` table that we use to source all the data presented on the "overview" tab. The three columns are:
- `totalcomplaints`: total hpd_complaints received by 311 ever
- `recentcomplaints`: total hpd_complaints received by 311 over the last 3 years
- `recentcomplaintsbytype`: an array of complaint _types_ and their frequency, ordered from most frequent to least, over the last 3 years
Note that I chose the 3 year cutoff totally arbitrarily. My thinking was that folks would want to know what kinds of complaints have been issued most recently, but that's obviously subjective...

Add hpd_complaints data to wow_bldgs table

---

wow/csvutil.py
wow/views.py

So, given that #457 has been merged and deployed to our auto-updating instance of NYCDB, the new hpd_complaints data that we added is now, by default, part of the CSV data export that users receive when clicking on the "Export Data" button on WOW. We can think of this as a nice little "soft launch" (or even an "easter egg") of the new data before we actually bake it in to our front-end somewhere.
In the meantime, though, I want to format the `recentcomplaintsbytype` column as the default json structure is hard to read.

Improve format for `recentcomplaintsbytype` column in CSV export

---

client/src/components/APIDataTypes.ts
client/src/components/PropertiesList.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/util/helpers.ts

This PR adds a new section to the react table on the Portfolio Tab called "HPD Complaints", that includes 3 new columns of data:
- **Total**: count of all complaints ever called in to 311
- **Last 3 Years**: count from just last 3 years
- **Top Complaint**: most common complaint type from last 3 years
One funky thing that this PR does is [add a new function to our helpers.ts file](https://github.com/JustFixNYC/who-owns-what/pull/461/files#diff-a7c84dff5c3235f5b41a5d1a818116d17fd0f0edb64977c68ab99a3fe97d660c) that internationalizes the complaint types that show up in open data.

Add hpd complaints data to Portfolio Tab

---

client/public/index.html

We got this message from FullStory via email:
> We are preparing to update some of our infrastructure, and as a result if you haven’t updated your snippet since October 30, 2019 you will need to update the FullStory snippet on your site by July 13, 2021 to avoid a disruption in session recording.
So, this PR is simply updating the snipped that FullStory provided.

Update FullStory script tag

---

wow/tests/test_views.py
wow/views.py

Sometimes the `ownernames` field of the query used to export CSVs is `NULL`, which we haven't been accounting for until now.

Handle CSV export when ownernames is null.

---

client/src/components/Subscribe.tsx
client/src/google-tag-manager.ts

This logs a `jf.subscribeToMailingList` event whenever the user successfully subscribes to our mailing list.  It is largely based off https://github.com/JustFixNYC/tenants2/pull/850.

Log GTM event when a user subscribes to mailing list.

---

sql/registrations_with_contacts.sql
tests/test_sql.py

In preparation for implementing Tahnee's new redesign of "Landlord Info" on the WOW Overview Tab, this PR adds a new column to the `registration_with_contacts` custom table that includes _all_ HPD contact names and corporation names, with associated addresses, in one single json object. 
In turn, this PR will subsequently add this new field called `allcontacts` to the end of the `wow_bldgs` table, since the SQL to generate the `wow_bldgs` table arbitrarily selects all columns from the `registration_with_contacts` table. Therefore, we should be able to start using this new column of data on the front-end right away.

Add `allcontacts` field to registration_with_contacts table

---

wow/datautil.py
wow/dbutil.py
wow/tests/test_datautils.py
wow/tests/test_dbutil.py
wow/views.py

This builds upon #478 by modifying the underlying database cursor to properly deserialize jsonb content from Postgres.  This is actually the default behavior of Python's Postgres package, psycopg2, but it's [overridden by Django][1]; this restores the default behavior within the scope of a single cursor.
A regression test has also been added to ensure that we'll know if this fix ever breaks (which could happen if Django decides to change its implementation somehow).
[1]: https://code.djangoproject.com/ticket/31991

Automatically deserialize jsonb in SQL queries.

---

client/src/assets/img/accordionchevron.svg
client/src/components/APIDataTypes.ts
client/src/components/Accordion.tsx
client/src/components/DetailView.tsx
client/src/components/Indicators.tsx
client/src/components/UsefulLinks.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/Accordion.scss
client/src/styles/App.scss
client/src/styles/DetailView.scss
client/src/styles/Indicators.scss
client/src/styles/spectre.scss
client/src/util/helpers.test.ts
client/src/util/helpers.ts
wow/views.py

This PR implements [Tahnee's designs](https://www.figma.com/file/w2eo2tq6YEbVW06rFF0jA4/Summer-2021-Sprints?node-id=47%3A2) that more clearly organize and spell out all of the contact names and corporations associated with a building on WOW. While mostly a styling and html structure change, this PR makes use of #477 in that it properly shows all entity names with their associated business addresses (unlike before).
Beyond updating the Detail View on the overview tab, this PR changes the look and feel of the "useful links" section to make it more compact, which shows up on both the overview and timeline tabs.
One small win: the various expandable menus and text boxes in this PR were ALL implemented with the `<summary><details>` native HTML elements! No special JS needed! Also they are all …

Restructure how landlord contact info is displayed on the Overview Tab

---

client/src/components/DetailView.tsx
client/src/components/UsefulLinks.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

Oops! Originally, we were only translating the word "ACRIS" in the link "View documents on ACRIS." This should fix things. This PR also updates some text on the detail view.

Fix `<Trans>` tag for ACRIS link, and update text

---

client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/util/helpers.ts

Shoot! We totally forgot to add "Corporation" as an addition title for an HPD contact. Good thing our rollbar caught this very quickly and we had a good fallback mechanism. Anyway, fixing this for now and adding in the translation manually for expediency.

Add Corporation as an HPD Contact type

---

client/src/components/Indicators.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/Indicators.scss

This PR removes an old link to an AirTable form that we have had on the Timeline Tab since it's launch many many years ago.

Remove old feedback form from Timeline Tab

---

client/src/styles/DetailView.scss

This PR tweaks some CSS to make sure that on Internet Explorer, we are hiding the "Summary" part of the `Learn more` accordion menu on the Detail View but still showing the full text.

Make sure "Learn More" content is visible on IE

---

client/package.json
client/src/components/Modal.tsx
client/src/containers/App.tsx
client/src/i18n.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/App.scss
client/src/styles/Modal.scss
client/yarn.lock

This PR replaces our standard navbar of links in the header with a hamburger menu once the viewport is smaller than a desktop or landscape tablet. The hamburger menu includes all original links from the navbar, with the only difference being that instead of the `EN/ES` toggle, we now show the full language name of whatever language the user is _not_ currently seeing on the site (see the new `<LocaleSwitcherWithFullLanguageName>` component). I also added an overlay to gray out the main content of the page when the user has the hamburger menu open. 
TODO:

Add hamburger menu to header on mobile

---

client/package.json
client/src/containers/App.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/yarn.lock

This PR makes use of the [widont package](https://www.npmjs.com/package/widont) (that we use on the justfix-website) to remove any single-word second lines from the title link on the header nav bar. This problem specifically arose with the _Spanish_ title as it was too long to fit on one line. Now, instead of looking awkward with a trailing "York" on the second line, it looks much better:

Remove widows from title link on navbar

---

client/package.json
client/src/components/PropertiesList.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/AddressPage.scss
client/src/styles/PropertiesList.scss
client/src/util/helpers.ts
client/yarn.lock

This PR makes various front-end improvements to the Portfolio Tab, with the main intention of improving our mobile experience. These include:
- Fix in place the first "Address" column
- Decrease width of Address column to ~90% (130px)
- Wrap text of Address entries onto 2+ lines
- Add Up down arrows in headers to indicate that data can be re-ordered
- Include fade out rectangle on viewport edge for horizontal scroll (and remove it when reaching end of scroll)
- Make all column headers fully shown 
- Make all columns only resizable on desktop
UPDATE: This PR now includes some tooling to set the height of the first column header as fixed to avoid some very distracting jank on mobile devices.

Enhance Portfolio Tab experience for mobile users

---

client/src/styles/HomePage.scss

This quick styling change removes some awkward spacing on the homepage warning banner introduced by #482.

Remove bottom margin from paragraph within homepage banner

---

client/src/components/PropertiesList.tsx

This memoizes the portfolio table via [`React.memo`](https://reactjs.org/docs/react-api.html#reactmemo) in an attempt to improve performance, particularly on IE11.
As far as I can tell via IE11's profiler, the majority of delay is now caused by layout:
> ![image](https://user-images.githubusercontent.com/124687/125527910-f82b8d5f-9cf3-4858-a9ae-81900839ff88.png)
I'm honestly not even sure how much it helps to make the table a pure component, though I guess it can't really hurt.  I suppose it does make the code a bit more complex, though.

Attempt to memoize the portfolio table.

---

client/src/components/Dropdown.tsx
client/src/components/Indicators.tsx
client/src/components/IndicatorsDatasets.tsx
client/src/components/IndicatorsTypes.tsx
client/src/containers/App.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/App.scss
client/src/styles/Dropdown.scss
client/src/styles/Indicators.scss

This PR condenses the whole UI navigation of selecting a dataset to view on the Timeline Tab. Using Tahnee's designs, I implemented two accessible dropdown menus that allow the user to select a dataset and a "time span" from lists that can be arbitrarily long. 
My implementation involved factoring out a new component called `<Dropdown>` which is shared between the header hamburger menu and this new feature. The new component has accompanying styles in `Dropdown.scss` as well.
Note: you'll notice I actually built on some minor refactoring in #500, specifically my work making the list of datasets and timespans to choose from more DRY. This PR will likely merge sooner than #500 so I felt that work needed to be reflected here first. I will take responsibility and work through any merge …

Restructure how datasets are selected on the Timeline Tab

---

client/src/components/UsefulLinks.tsx
client/src/containers/NotRegisteredPage.tsx
client/src/containers/NychaPage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/NotRegisteredPage.scss

This PR is a restructuring of the UI of our "Not Registered" page. Specifically, it replaces the buttons under the "Useful Links" header with our `<UsefulLinks>` component. This is a response to a request from the Program team about having the HPD Building Profile link available, even for non-registered properties.
Note that this PR also fixes a minor bug where we were not including a proper google event tag with these outbound useful links on the Not Registered pages.

Show full list of useful links on Not Registered pages

---

client/.env.local.sample
client/src/containers/App.tsx

This PR removes an old env variable that we no longer use because of changes to Chrome and other browsers.

Remove ENABLE_OLD_BROWSER_WARNING feature flag

---

.circleci/config.yml

Soooo... upon trying to create a PR on who owns what this morning, we detected that our CircleCI build pipeline was failing, precisely when it was trying to download packages using Node 14 vs. the specified Node version 12 that we define within the Dockerfile as well as our engines list in `package.json`.  The problem seemed to stem from the use of the CircleCi docker image called `python:3.6-node`, which according to the [CircleCI docs](https://circleci.com/developer/images/image/cimg/python) pulls in Node 14 to accompany python 3.6. 
Our working theory was that there was a python patch (Specifically 3.6.13 --> 3.6.14) that triggered CircleCI to update their image in a way that changed the associated Node version to 14. While we aren't 100% sure, specifying python version 3.6.13 in the …

Specify exact python version to use for CircleCI container

---

client/src/components/WowzaToggle.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This PR fixes a bug where the "Switch to New/Old Version" button on the Address Toolbar wasn't showing any text within it's <Trans> tags. Turns out it was because we were importing the Trans component from lingui/react and NOT lingui/macro which is where it should come from.

Fix incorrect lingui import on WowzaToggle

---

client/src/components/FeatureCalloutWidget.tsx

This PR removes the possibility of our feature callout widget being defaulted to open on page load. Now it is always closed. We still report the initial open/closed state to Amplitude though, just to keep our analytics somewhat consistent.

Remove AB testing from feature callout widget

---

client/package.json
client/src/components/APIClient.ts
client/src/components/APIDataTypes.ts
client/src/components/AddressToolbar.tsx
client/src/components/ExportData.test.tsx
client/src/components/ExportData.tsx
client/src/containers/AddressPage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/yarn.lock

Inspired by #526, this PR implements a similar refactoring of our Export Data feature such that it no longer re-submits a request to our database for portfolio data and instead takes the portfolio data cached in our client state and generates a CSV for download purely using javascript. One less network request our user's browsers now have to make, yay!
I ended up using the https://github.com/Bunlong/react-papaparse package to help with CSV export functionality—it is Typescript friendly and also seems to be frequently updated/well maintained.

Refactor Export Data feature so that it doesn't require an API call

---

client/src/components/APIDataTypes.ts
client/src/components/ComplaintsSummary.tsx
client/src/components/PropertiesSummary.tsx
client/src/components/SummaryCalculation.test.ts
client/src/components/SummaryCalculation.ts
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/state-machine-sample-data.ts

This PR adds a new section to the Summary tab called "Complaints called in to 311" on Who Owns What that shows users a sum of 311 complaints across the portfolio, as well as a list of the most common complaint types.

Add 311 complaints section to summary page

---

client/src/components/ViolationsSummary.tsx

This PR is a long overdue update of a variable on within the `<ViolationsSummary>` component that quantifies the average number of violations per residential unit across the entire city. The number is manually calculated by writing a super simple query to nycdb.
I've always wondered if we should. find a way to automate the process of updating this... the number has maybe changed once or twice over the last 3.5 years and only by 0.1 (which is what we round the metric to on the front-end). So, it always felt like too much overhead to make a network request, but maybe there is another option?

Update statistic for "average violations per residential unit citywide" on Summary tab

---

client/src/containers/App.tsx
client/src/containers/BBLPage.tsx
client/src/routes.tsx

This PR builds out the "bbl-based" url entrypoint into WOW by allowing users to specify in this URL scheme whether they want to use the new 'wowza' portfolio mapping algorithm or not. 
Basically, we have an existing feature where users can access WOW via a url like `/en/bbl/4015640058` and get redirected to the stable address page on WOW, which in this case is `/en/address/QUEENS/41-25/CASE%20STREET`. This is particularly helpful when you have a whole list of bbls (say, in a spreadsheet), and you want to quickly generate a list of direct links to WOW from it. 
So, this PR is essentially just adding an extra feature to these bbl-based urls where you can now ALSO define whether you want to access a new wowza page or a regular page.
NOTE: since we are introducing another route path, I …

Allow "wowza" prefix within bbl-based URLs

---

client/src/util/helpers.test.ts
client/src/util/helpers.ts

This PR adds a new helper function called `getLandlordNameFromAddress` which takes in an AddressRecord object and finds the name of the landlord (or names, if there is a rare edge case where there is more than one) and returns a string array with the name(s) inside.

Add `getLandlordNameFromAddress` helper function

---

wow/views.py

It has been more than two months since we updated the schema of our `address_indicatorhistory` endpoint on the WOW backend (https://github.com/JustFixNYC/who-owns-what/pull/500). This PR removes some extra code we wrote that had made the old names of certain fields still available to cached front ends. It's time... I think?

Remove deprecated fields from indicatorhistory endpoint

---

client/src/util/helpers.test.ts
client/src/util/helpers.ts

I noticed two helper functions within `helpers.ts` that are not used anywhere in the codebase and also don't seem particularly novel or helpful. Removing them to reduce code bloat!

Remove old helper functions we no longer use

---

client/src/components/DetailView.tsx
client/src/components/PortfolioGraph.test.tsx
client/src/components/PortfolioGraph.tsx
client/src/components/PropertiesSummary.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

This PR refactors our `<PortfolioGraph>` component to dynamically add on nodes to the graph visualization for the user's Search Address, as well as the Detail Address if it differs from the Search Address. The idea behind these additional nodes was to create some feature parity with the "How is this building associated..." feature on the old WOW:
Now, when users click on this link, they are redirected to the Portfolio Graph (currently on the Summary tab) to see how their search address is related to the address in focus on the Overview tab:
This is particularly important because in order to build trust with our users regarding this new portfolio method, we need to have some feature that illustrates how each building in the portfolio connects back to the original address they searched. …

Add search address and detail address nodes to portfolio graph visualization

---

client/src/components/PropertiesList.tsx

This PR makes both the  BBLs & addresses clickable on the Portfolio tab, linking them back to the detail view just like the "View Detail" arrow button already does.

Make Address and BBL clickable on Portfolio Tab

---

client/public/index.html

This PR addresses a request from WholeWhale: 
> would it be possible for you to whitelist the Facebook pixel on WoW domain? we identified this as the source of the issue for why we couldn't use the conversion we set up in our test run.

Add Facebook Pixel whitelisting code snippet

---

client/src/components/PortfolioGraph.tsx
client/src/containers/App.tsx
client/src/containers/HomePage.tsx
client/src/routes.tsx

This PR makes some minor adjustments to the WOWZA view of who owns what in order to make it easier for beta testers to navigate the site:
- the portfolio graph on the summary tab no longer takes up the full page, and has a legend and new styling for legibility
- we now save whether the user is searching normally or searching using the new WOWZA method in the actual url of the homepage itself (users at the path `/` are searching normally but when they are at the path `/wowza` they are searching using the new method)
- toggling between the two methods on the site is now more comprehensive with a new button on the homepage and dynamic page links in the header menu

Make new WOWZA demo site easier to navigate for beta testers

---

.circleci/config.yml

Fixes issue with deprecated version of Ubuntu machine: 
```
Hello,
We are deprecating Ubuntu 14.04-based machine images on CircleCI in preparation for an EOL on Tuesday, May 31, 2022 to ensure your builds remain secure. For a detailed overview of how this will affect your workflow, read the blog article here.
We will also be conducting temporary brownouts on Tuesday, March 29, 2022, and again on Tuesday, April 26, 2022 during which these images will be unavailable.
We are contacting you because one or more of your projects has a job that either:
does not specify an image (uses machine: true in config)
explicitly uses an Ubuntu 14.04-based image
Jobs that do not specify an image default to using an Ubuntu 14.04-based image.
The project(s) using an image based on Ubuntu 14.04 are: …
```

Specify Ubuntu image version in circleci deploy config

---

portfoliograph/landlord_index.py
tests/test_sql.py

this PR adds the unique `objectID` for each record that Aloglia requires. It is created as a hash of the rest of the contents of the record (`{"portfolio_bbl": 1234567890, "landlord_names": "name1, name2"}`), so that later we can use the hash to determine if we need to update the record, and hopefully save us some Algolia operations/credits.
Also add tests of this new hash, and adjust the existing tests now that we can ensure consistent ordering of landlord names in the concatenated string.

add Algolia objectID as hash of contents + tests

---

portfoliograph/landlord_index.py

This PR makes sure that we are replacing our entire Algolia index when updating.

Replace ALL objects when updating our Algolia landlord search index

---

portfoliograph/graph.py

When building the `wow_portfolios` table we previously included only `HeadOfficer, IndividualOwner, CorporateOwner`, this PR adds `JointOwner` as well. Sam identified that we should add JointOwner already, since some only show up in that category. But we now also might need to include it to ensure that all `wow_bldgs` records appear in `wow_portfolios`, since we found that not all of them do currently (see second SC card)
[sc-8951]

add JointOwner to wow_portfolios table

---

portfoliograph/landlord_index.py
tests/test_sql.py

This PR adds a new helper function called `get_corpname_data_for_algolia` which grabs the names of all corporations listed in the `wow_bldgs` as well as one of their associated bbls and creates a new individual algolia search record for each unique corporation name. We then just append these records to the list we send our Algolia app when updating the landlord search index.

Add corporation names to the Algolia landlord search index

---

client/src/components/PortfolioGraph.tsx
client/src/components/PropertiesSummary.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/PropertiesSummary.scss

This PR makes some minor styling and wording adjustments to the Summary tab to make the presence of the portfolio network graph on that page make sense.

Adjust placement and context of portfolio network graph

---

client/src/components/PropertiesList.tsx
client/src/util/helpers.test.ts
client/src/util/helpers.ts

This PR makes sure that `JointOwner` names are shown on the "Owners" column of the Portfolio tab, and that `JointOwner` names also can define the `name` property of a node on the portfolio network graph visualization.

Add "Joint Owner" as a valid owner contact type across Who Owns What

---

client/src/components/AddressToolbar.tsx
client/src/components/DetailView.tsx
client/src/components/LandlordSearch.tsx
client/src/components/LegalFooter.tsx
client/src/components/WowzaToggle.test.tsx
client/src/components/WowzaToggle.tsx
client/src/containers/AddressPage.tsx
client/src/containers/App.tsx
client/src/containers/BBLPage.tsx
client/src/containers/HomePage.tsx
client/src/routes.test.tsx
client/src/routes.tsx
netlify.toml

This PR makes sure that all of our `/wowza` pages are now found at the root, and all of the existing root pages, that utilize the old version of WOW, have been moved to the `/legacy` directory. This PR also simplifies our route structure to make sure that all pages, including our about, methodology, etc., have a "legacy" and wowza version so users stay within their selected version of the site upon navigation.

Migrate WOWZA routes across the site to the default root pathname

---

client/src/components/PortfolioGraph.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/PropertiesSummary.scss

This pr adds a very simple set of zoom buttons onto our Cytoscape network visualization on the summary tab.

Add custom zoom widget to portfolio graph viz

---

client/src/components/WowzaToggle.tsx
client/src/routes.test.tsx
client/src/routes.tsx

This PR fixes an issue where toggling between old and new WOW portfolio methods on the homepage made the page elements and assets flicker awkwardly. Turns out this was due to the fact that any switch between portfolio methods caused a page refresh. I changed our toggle logic to _only_ trigger a page reload when switching portfolio methods on an internal address page—which we need to do to load in new data for the page.

When changing portfolio methods, only refresh the page if it's an address page

---

client/src/components/WowzaToggle.tsx
client/src/containers/App.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/routes.tsx

This PR creates an internal redirect from all old `/wowza` paths to the root directory of the site where the wowza portfolio mapping is now currently found. This is in response to some user testers having issues on the demo site with old links to portfolios.

Create an internal redirect from the old WOWZA path

---

portfoliograph/graph.py
portfoliograph/table.py

This PR creates an interim fix for the issue of [bbls belonging to multiple landlord portfolios](https://app.shortcut.com/justfixnyc/story/8989/multiple-wow-portfolios-records-cover-same-bbl-set) on WOWZA. So, we changed our SQL query in generating the raw data for the networkx graph to make sure that only one landlord contact corresponds to each registrationid from HPD. In the rare cases where there are multiple owners on a given registration, we have a ranking for prioritizing which owner type we define as the best one to use for portfolio generation. 
Given that the vast majority of these edge casey buildings belong to a portfolio of 1, these changes likely will not affect the scale of our portfolio generation very much, even though we are trimming down the level of possible links a …

Ensure that only one landlord corresponds to a given `registrationid` from HPD

---

client/src/components/BigPortfolioWarning.tsx
client/src/components/LazyLoadWhenVisible.tsx
client/src/components/PropertiesSummary.tsx
client/src/styles/PropertiesSummary.scss

This PR reduces jank by accounting for the lengthy load times of two new elements:
- The network visualization on the Summary tab takes a longggg time to laod for big portfolios, particularly [the huge one with 2500 bldgs](https://demo-whoownswhat.justfix.nyc/en/address/BROOKLYN/196/RALPH%20AVENUE). I made use of the `LazyLoadWhenVisible` component to allow the user to navigate to the Summary page and see all other content while the network viz loads with a loading icon.
- The image on the BigPortfolioWarning modal flickers on after you open the modal. I added a step to pre-load the image source when the actual warning _banner_ loads so that by the time the user opens the modal it is already loaded.

Lazy load the network visualization, and the photo of it within the Big Portfolio modal

---

client/src/components/PortfolioGraph.tsx

When a user selects a new address from the overview tab or portfolio tab, that triggers the addition of a new node to our network viz to show which landlord name owns that new selected property. Before, this new node would by default render in the center of the graph, with a long overlapping edge connecting it with wherever it's related landlord name node is. This would create a very awkward and busy looking graph, so this PR makes sure that we re-render the graph layout whenever the user's selected detail address changes.
This PR also reduces edge overlap overall and makes sure our node labels are visible from more zoom extents.

Make sure network viz redistributes nodes after adding detail address

---

client/src/containers/AddressPage.tsx

This PR puts the functionality that checks the Address Page component's url structure behind the REACT_APP_ENABLE_NEW_WOWZA_PORTFOLIO_MAPPING feature flag. This way, we can push all of our current changes to production without actually launching the new WOWZA portfolio mapping method yet.

Only check urls when WOWZA portfolio mapping enabled

---

client/src/containers/HomePage.tsx

Oops! This PR fixes a weird bug where if a user searched and address from the homepage in Spanish, it would redirect them to an address page in English! Not sure how we missed this, but this PR ensures that the user's locale gets passed on correctly when they search an address.

Make sure the user's locale stays intact on address search

---

client/src/components/LandlordSearch.tsx

This PR addresses a very unfortunate problem with the Algolia instantsearch library: where any re-rendering of the <InstantSearch> component causes a duplicate network request to Algolia, which in turn costs us one of our precious search credits that we only get a certain amount of. So, this PR does some refactoring to reduce the number of times we re-render our custom LandlordSearch component to mitigate the problem.
Previously, our search bar was making 2 duplicate network requests on every user keystroke, which meant we were draining credits twice as fast as we should. I was able to optimize our rendering processes so that now, we make:
- 1 network request on initial renter of the search bar (this is expected)
- 2 network requests on typing in our first character
- 1 network request on …

Reduce number of algolia network calls in LandlordSearch component

---

client/src/containers/AddressPage.tsx
client/src/styles/AddressPage.scss

On an address page there is a line at the top saying "your search address is associated with __X__ other buildings" with the number underlined, and it feels like you should be able to click it but it wasn't a link. This PR makes it a link to open the Portfolio tab. I didn't make this focusable because it felt like this would only be confusing and redundant since you can toggle through all the available tabs already, but let me know if it should be or there is any other accessibility change I should make. 
[sc-9182]

link from number of buildings to portfolio tab

---

client/src/components/LandlordSearch.tsx

This PR builds on #633 and #630 to even further reduce the number of network request we make to Algolio when a user searches their landlord name. Specifically, we now do not trigger a network request for a search until the user has typed in 2 characters into the search bar.
The basic idea behind this PR is that Algolia provides their own state and state-updater functions for the `<SearchBox>` component, called `currentRefinement` and `refine` respectively, that keep track of the current search query and allow you to update it on changes to the form input, which by default triggers a network request. I created our own internal copy of this state with `searchQuery` and `setSearchQuery` so we can keep track of user inputs without triggering any Algolia network request. Then, in our useEffect …

Don't request Landlord Search results until user types 2 characters

---

client/src/components/Accordion.tsx
client/src/components/AddressToolbar.tsx
client/src/components/Amplitude.ts
client/src/components/DetailView.tsx
client/src/components/ExportData.tsx
client/src/components/Indicators.tsx
client/src/components/IndicatorsDatasets.tsx
client/src/components/PropertiesList.tsx
client/src/components/Subscribe.tsx
client/src/components/UsefulLinks.tsx
client/src/containers/AddressPage.tsx
client/src/containers/App.tsx
client/src/i18n.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

After talking with Tahnee and Risha last week we identified a bunch of analyses they'd like to see in amplitude, and so this PR adds more event logging to make sure we have all the data necessary. 
Mostly I just was simply adding logs, but I also noticed that an existing one on the timeline period switcher was logging twice with each click, so I moved that and fixed it. I also added an optional `onClick` to the `Accordion` components props so you can more easily log the click to expand event.

add amplitude logging on more events

---

tests/exported_test_data.sql
wow/sql/address_portfoliosize.sql
wow/tests/test_views.py
wow/urls.py
wow/views.py

This PR addresses an issue where the count of associated properties for a building on ANHD's [DAP Portal](https://portal.displacementalert.org/property/3012380016) did not match up with the new count of associated properties on Who Owns What given our new portfolio mapping method.
Turns out that ANHD's [DAP Portal](https://portal.displacementalert.org/property/3012380016) actually relies on a special API endpoint (`/api/address/dap-aggregate`) we created just for them that sends their tool a bunch of aggregate information on a building's portfolio if they send a request with a bbl in it. However, this API endpoint still references the old portfolio method, so in order to fix this, I created a new API endpoint at `/api/address/dap-portfoliosize` that retrieves portfolio sizes based on our …

Add API endpoint to get portfolio size for DAP Portal

---

netlify.toml

This PR builds on investigative work in https://github.com/JustFixNYC/justfix-website/pull/204 to redirect all URLs at the current `demo-whoownswhat.justfix.nyc` DEMO SITE domain to `demo-whoownswhat.justfix.org`, preserving all paths in the redirect.

Redirect WOW demo domain from .nyc to .org

---

client/public/_redirects

It seems that the redirect config in our `_redirects` file is being read over our `netlify.toml` configuration. This is a test to see if moving a redirect specification between the two files changes behavior.

Test: add netlify redirect to _redirects file

---

client/public/index.html

The problems continue with verifying our domains (wow and org site) with facebook. The scraping tool FB uses is not successfully navigating the redirect from `.org` to `.org/en` and so it's not seeing the tag we first added in #652 to Page.tsx. This PR adds the same meta tag to index.html directly as well. Once we finally sort out exactly what the problem is I'll come back and clean this up so it's not duplicated.

add fb domain code to index.html

---

requirements-dev.txt

pyproj was removed here: https://github.com/nycdb/nycdb/pull/183/files so this removes it from the dev requirements as well (was getting an error when I attempted setup with pyproj included)

Remove pyproj from Docker requirements

---

client/public/robots.txt

We've been getting a lot of bots hitting the `wow-django.herokuapp.com/api/*` path around midnight, and at that time some functions get redefined and are unavailable for a short window leading to lots of errors getting logged in rollbar. We are also working on solving the function issue directly to eliminate/reduce that window, but we also don't need bots crawling the `/api/` anyway so we'll add this robots.txt file to disallow that path. 
[sc-11028]

add robots.txt to disallow /api/

---

client/src/containers/App.tsx

We have an old version of the BBL route that is still being used by ANHD's DAP Map and these are going to the `/legacy` version of WOW portfolio mapping method. This PR updates the route so they all go to the new WOW version.
[sc-11155]

use new portfolio mapping for bbl parts route

---

client/src/components/StickyModal.tsx
client/src/styles/_modal.scss

- adds z index
- css class is a little gnarly but it basically bumps up the margin when the overview or portfolio tabs are active, so that the user can click/see things under the survey CTA:
- small cleanup in StickyModal.tsx

Fix sticky modal z-index, positioning on Overview and Portfolio tabs

---

client/src/containers/App.tsx
client/src/styles/_button.scss
client/src/styles/_modal.scss
client/src/styles/_vars.scss

[sc-11179]
- add exclamation point to label copy
- make button a fixed 40px height
- change drop shadow opacity to 0.25
- adjust sizing and positioning of the close button
- increase margin-right for the modal to prevent scrollbar overlap (desktop only)
- increase the font weight to semibold/600 (mobile only) and the size to 18px

Small CSS adjustments for survey button

---

client/src/containers/App.tsx

quick fix to display the survey end screen. instead of updating the state (which causes a re-render and closes the embed automatically), we set a flag and update the cookie when the survey is exited.

Don't update survey cookie until the survey is closed

---

client/src/components/WowzaToggle.tsx
client/src/containers/App.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

In anticipation of portfolio filter release and deprecation of the legacy portfolio method, we are updating the site-wide banner to let folks know legacy version won't be available starting March 2023. 
[sc-11493]

update legacy banner language

---

client/src/containers/App.tsx
client/src/containers/HomePage.tsx
client/src/data/about.en.json
client/src/data/about.es.json
client/src/data/how-it-works.en.json
client/src/data/how-it-works.es.json
client/src/locales/en/messages.po
client/src/locales/es/messages.po

As part of our WOW legacy deprecation plan we are updating the copy on the banner, and adding a note to the about page. 
We also remove the "new" pill for the search by landlord name feature on the homepage. 
[sc-11583]

Legacy deprecation banner update

---

client/src/containers/App.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

Switch back the text on the legacy version of the banner to remove reference to a deprecation date. 
[sc-11583]

revert legacy banner copy for old version

---

client/src/components/PortfolioFilters.tsx
client/src/styles/PortfolioFilters.scss
client/src/styles/PortfolioTable.scss
client/src/styles/_button.scss
client/src/styles/_typography.scss
client/src/styles/_vars.scss

Moved the new design system typography out of _vars, and used those mixins/variables where possible (we're still not using much of the new system)
This PR also includes a refactor of the portfolio filter styles, simplifying things now that the markup is mostly finalized and to make things easier to adapt for mobile.

reorg design system typography, refactor filter styles

---

client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/styles/Multiselect.scss
client/src/styles/PortfolioFilters.scss
client/src/styles/_alert.scss
client/src/util/helpers.ts

This PR adds support for mobile to the filter bar. Makes the basic changes to the styles of filter components and the bar, plus adds the fullscreen wrapper of all filters - and the scroll snapping and shadow effects. Plus a small fix to the handling of min-max errors, and its default values I caught while in here.
Also included is an update to the filter input styling on desktop and mobile so they read more clearly as inputs (not full width, white background)
Not included is the mobile-specific behavior of applying in-progress filters when the user clicks outside of that filter's dropdown. It seems like this will require some more substantial reorganization of how/where that state is managed to allow for this. I'll make a separate PR for this once I figure things out.
[sc-11706] …

Filters mobile

---

client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/PortfolioFilters.scss
client/src/styles/_alert.scss

This PR adds the "toast" notifications that pop up when results are updated. 
[sc-11711]
They slide up from the bottom, stay for 5 seconds, then slide out. If you hover on them it pauses the animation. They have [`role="status"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/status_role) so they're read out on screen readers (after learning about this I also went through and added this role to other alerts within filters that made sense). 
In addition to the toasts, there is an in-line alert for when there are 0 results. 
On mobile, they only appear after you close the fullscreen filters menu, and so if you apply multiple filters within one trip into the filter menu then multiple toasts pop up at once. There is a desired priority given by Design and this is given …

add "toast" notifications on results

---

client/src/components/PortfolioTable.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/PortfolioFilters.scss
client/src/styles/PortfolioTable.scss

Apply styles for expanded row of owner contacts for MVP. Design will provide final styles later, but for MVP they just wanted something basic. This PR just adds proper internationalization following what we do on overview page, and adjusts the positioning so the names always appear directly under the owner name. It's a bit awkward on mobile since there is just so little horizontal space, but with scrolling it can work.
[sc-11715]

style expanded owner contact row for mvp

---

client/src/components/PortfolioFilters.tsx

When filter accordions are opened the focus is initially set to the filter input (search bar for multiselect and min input for min-max select)
The multiselect component already uses the component ID to create an id for the search bar input, so I followed the same pattern for the min-max component.
[sc-11770]

focus inputs on opening filter accordions

---

client/src/components/AddressToolbar.tsx

Anticipating the "map/table" toggle design wanted to change these button styles so it doesn't look like the same sort of thing. 
before
after
[sc-11499]

use same style for "new search" button as for "export"

---

client/src/styles/PortfolioFilters.scss

Adjust the styles for the mobile filter menu to make sure all of the individual filter dropdowns stay stacked together (previously everything below the active one was hidden).
This also make a small fix to the zipcode input that was causing horizontal scroll
[sc-11884]
[sc-11809]

Filters mobile menu

---

client/src/styles/PortfolioFilters.scss

Fixes a couple small bugs for the RS units toggle on mobile:
* It was getting squished when the other filter accordions were expanded
* It was staying underlined after toggling it off (mobile hover state)
[sc-11939]
[sc-11926]

fix RS units toggle height and hover on mobile

---

client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/styles/Multiselect.scss
client/src/styles/PortfolioFilters.scss

A few changes related to the multiselect component:
* The dropdown options are changed so that selected options aren't removed from the list. Instead they have a checkbox to show if they are selected. And for keyboard navigation/hover they are still underlined. 
* The component is improved for tab navigation/screen readers, but it's still not working on all platforms, and a follow up PR will address that. For now this makes sure that escape closes the option list returning to the searchbar (so you don't get cught in the often super long lists). The screen reader experience is working mostly in Chrome/OSX, but not on Windows. 
* The Multiselect component styles are cleaned up so that it's all nested under the component class
* The font size for the searchbar input is increased to 16px to …

multiselect dropdown - add checkboxes, keep searchbar text, keep selected options in list

---

client/src/styles/PortfolioFilters.scss

Various QA fixes for mobile filter menu
* Slide up to fill screen
* Sticky header shadow - smaller/darker, only on top
* Hide page from showing through around rounded corners
* was using `outline` for this, but it doesn't follow border-radius on safari. plus now it needs to be animated with slide
* remove `max-height` to prevent internal scrolling for nested filer accordions, so whole menu scrolls instead
* this should also fix the buggy scrolling when there are active selections
https://user-images.githubusercontent.com/16906516/228920984-c226451d-89eb-499f-a080-ea2cbcf449b1.mov
* Also, reduce the width of the landlord search bar/dropdown to leave room for scrolling.  
[sc-11993]
[sc-11875]
[sc-11879]
[sc-12095]

sticky header shadow, slide in, scrolling, hide background page

---

client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/Multiselect.scss
client/src/styles/PortfolioFilters.scss

Fixes to the handling of errors in Min/Max building size inputs, and the styling of the binding size filter on desktop/mobile
For the errors:
* Apparently some browsers still allow characters in numeric inputs, so I found a work around to prevent that.
* I've fixed the validation so errors are raised when:
* min or max is a negative value,
* min input > max input
* min input > max range
* max input < min range
* The error alerts will now have explanations for all these cases
For styles, there were a bunch of little changes, but here's what it looks like now:
[sc-11953]
[sc-11638]

fix min-max errors and units filter styles

---

client/src/styles/PortfolioFilters.scss

Reduce negative space between "new" label and "filters" label.
[sc-11593]
before: 
after:

Reduce negative space between "new" label and "filters" label.

---

client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/components/PortfolioTable.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/util/helpers.ts

ZIP Code filter QA fixes

---

client/src/components/PortfolioFilters.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/PortfolioFilters.scss

Update design for the filter results info row.
Before: 
After:
[sc-11607]

updates styles for filter results info

---

client/src/components/PortfolioFilters.tsx

Previously we made all the multiselect filter accordions automatically focus in the search bar input on opening (#721). This PR removes that for mobile only. 
[sc-12092]

only auto-focus filter inputs on desktop

---

client/src/styles/Multiselect.scss
client/src/styles/PortfolioFilters.scss

[reduce letter spacing for filter apply buttons](https://github.com/JustFixNYC/who-owns-what/commit/8cc98cda418c646a267fee02ba54c1559ba087b1)
[sc-11619]
[increase letter spacing for multiselect "+ X" more chip](https://github.com/JustFixNYC/who-owns-what/pull/738/commits/944f8d0a1e27adda770a2e4ba8320cb3b923c548)
[sc-11633]
[fix spacing between multiselect selected chips](https://github.com/JustFixNYC/who-owns-what/pull/738/commits/6c44fb961a645db4a67f0adfae4b2e9dba076c5d)
[increase letter spacing for RS unit filter toggle](https://github.com/JustFixNYC/who-owns-what/pull/738/commits/c8a60a2c216c7614cb12e275f76a4011ce482266)
[sc-11596]
[center multiselect input text and placeholder grey-600](https://github.com/JustFixNYC/who-owns-what/pull/738/commits/a86e92de8b6cc12dbb06f2420a469a707c8860d …

Various Filter QA changes to styles 

---

client/src/components/PropertiesList.tsx

Previously we weren't sending any extra data along with our google analytics events in WOW, we only did for Amplitude. This PR adds the same extra properties along with our events for portfolio table column sorts and address clicks. I'm doing just these two now so they can go to prod and I can make sure everything works correctly on GTM for updating the custom variables/tags for the events. After that there is another filters-specific PR to follow that sets up all the new events for filters.

add extra params for GTM on portfolio events

---

client/src/components/Amplitude.ts
client/src/components/MinMaxSelect.tsx
client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/components/PortfolioTable.tsx
client/src/components/PropertiesList.tsx

This PR adds a collection of analytics events - some are already in wow but needed to be added back after the table was completely rewritten for filters, and others are brand new to cover the filters interactions. All of the events have parity between Google and Amplitude, including the custom properties we send along with each (eg. portfolioSize, portfolioColumn, etc.). [sc-10784]
The way I'm actually logging the events in kind of awkward, because we have some common extra properties to send with them all, I tried to make them not too clunky when actually doing the logging, and we also have some frustrating inconsistencies between amplitude and google. Once we have everything up for filters, and can spend a bit of time getting settled into the new Google ecosystem of analytics tools, …

add analytics events for filters

---

client/src/components/PortfolioFilters.tsx

We've gone back and forth on this a few times. Most recently, on desktop only, when you opened the filter accordions it would automatically focus the inputs. This had already been disabled for mobile, and now this behavior has been removed from desktop as well. (Though the optional prop is retained in FilterAccordion in case we change our minds again later)
[sc-12270]

remove auto focus of inputs on opening accordions (desktop)

---

client/src/components/MinMaxSelect.tsx
client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/components/PortfolioTable.tsx
client/src/components/PropertiesList.tsx

For our multiselect filters all selections made from the options dropdown are saved in the multiselect component state as "pending" selections, then once "apply" is clicked that are confirmed and passed into the main filters context/state. We want to make sure things match user expectations, so this PR changes so that:
any selections that are not applied are cleared when the filter dropdown is closed
any applied selections persist in the filter when opened/closed
when all applied filter selections are cleared with the "clear all" button the "pending" selections should also be cleared from the multiselect component. 
Also, in doing this I realized there was some inconsistency with the types of the multiselect filter selections that needed to be fixed. No more `any` used in those!
For the …

Clear unapplied filter selections

---

client/src/styles/PortfolioFilters.scss

We changed the language for the multiselect filters from "clear" to "clear selections", and on desktop we ran out of room. So we are widening the filter dropdown. And now that there is more room, we decided to change the selected chips to be `flex-direction: row` so the spacing looks better.

widen zip filter for desktop, chips flex direction row

---

client/src/components/MinMaxSelect.tsx
client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/styles/PortfolioFilters.scss
client/src/styles/index.scss

We have been having problems with the mobile filter menu on IOS cause by layout shifts when the virtual keyboard appears. The way IOS (Chrome and Safari) handles the changing space is to keep the page the same size, but push it up and off screen at the top. 
This is their intended bahavior, but it has been causing some bugs as well. First, it would cause a permeant shift of the page that would persist even after closing the keyboard and exiting the mobile filter menu - leaving the whole portfolio table page with a black/white section at the bottom of the page. We found a workaround for this in #769, using JS to scroll the page once the filter menu is closed, and this fixed the layout back on the portoflio table page. 
Another problem we were having is that on the menu when the keyboard is …

ios mobile menu scrolling

---

client/src/components/PortfolioAlerts.tsx

I just noticed a typo in the event name for the GTM event tracking clicks on the overview page alert on the map directing users to use filters on the portfolio tab.

GTM event name typo fix

---

client/src/components/APIDataTypes.ts
client/src/components/Alert.tsx
client/src/components/DetailView.tsx
client/src/components/Multiselect.tsx
client/src/components/PortfolioFilters.tsx
client/src/components/PortfolioTable.tsx
client/src/components/PropertiesList.tsx
client/src/components/PropertiesMap.tsx
client/src/containers/AddressPage.tsx
client/src/containers/App.tsx
client/src/containers/HomePage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/HomePage.scss
client/src/styles/PortfolioFilters.scss
client/src/styles/PortfolioTable.scss
client/src/styles/PropertiesList.scss
client/src/styles/PropertiesMap.scss
client/src/styles/_alert.scss
client/src/styles/_minmaxselect.scss
client/src/styles/_multiselect.scss
client/src/styles/_scrollbar.scss
client/src/styles/_tabs.scss
requirements.txt

This PR continues our work on WOW for Collective Action adding filters to the portfolio tab - first the filter UI and updated table were added in #709, and this adds the map view.
We adapt the existing PropertiesMap component used on the Overview tab to be used on both tabs, adding a new prop to indicate the version to use. There are different point styles, a new selected building info alert, and logic for filtering the list of addresses based on the selected filters (passed through the same ContextProvider as we used for the portfolio Table view). 
Each MapBox map load is fairly expensive, so we try to only load it when necessary (the tab is in view), and also prevent multiple loads. In the WOW AddressPage component, where all of the contents of the tabs (overview, portfolio, etc) is …

add map view for portfolio filters

---

client/src/styles/Modal.scss
client/src/styles/PortfolioFilters.scss

After having the spanish translations added, I did a final QA pass and noticed a few minor issues. 
- The landlord info modal overflows the page. So I've just added a max height, so it will scroll if necessary. 
- before // after
- ![image](https://github.com/JustFixNYC/who-owns-what/assets/16906516/bcf5244a-39c3-4dda-a90d-9f8a37d9b488)
- The RS filter toggle text alignment is off when it wraps to a second line
- before // after
- ![image](https://github.com/JustFixNYC/who-owns-what/assets/16906516/571b60c4-aecf-466f-943f-1674818adfed)
- The map/table view toggle is a couple pixels smaller than the filter bars

last min QA fixes for map filters

---

client/src/components/AuthClient.ts
client/src/components/UserContext.tsx
client/src/containers/App.tsx
client/src/routes.tsx

* on logout, the user object was still being populated with undefined values in `email`, `verified` and empty `subscriptions`. turns out it's because of how the `postAuthRequest` was still returning a `response.json` even if the response was not 2xx. 
* redirects to home any time the user logs out from the nav bar while on pages that should require a login 
[sc-12766] [sc-12808]

User object not clearing on logout, Redirects from restricted pages

---

client/src/components/DetailView.tsx
client/src/components/PropertiesSummary.tsx
client/src/components/StreetView.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/DetailView.scss
client/src/util/browser.ts

The API for the dynamic google sreetview embed we use on the address page detail view is super expensive, and also the quality of the images has been declining (it's now common to be weird interiors of storefronts etc.). So we've decided to swap it with the way cheaper static streetview image we are already using on summary tab and have a link to google maps. 
[sc-11959]

change detail page streetview to static image

---

client/package.json
client/src/index.js
client/yarn.lock

In #787, when we had problems with the portfolio tab map not adjusting when the container height changed, we introduced a new package to use ResizeObserver. It is apparently supported by ~95% of browsers, but in the few cases it's not supported we are getting errors that it's not defined.
A [github issues thread](https://github.com/recharts/recharts/issues/2491) on the package repo explains that there is an alternative (the library [`resize-observer-polyfill`](https://www.npmjs.com/package/resize-observer-polyfill)) that can be assigned to `window.ResizeObserver` to handle these cases.
I tested this out by just first setting `window.ResizeObserver = undefined`, confirming it breaks, then using the polyfill and confirming it works again, and haven't had any problems. 
Only thing I wasn't …

add resize-observer-polyfill package

---

client/src/components/PortfolioFilters.tsx

The filter bar layout would break when changing from desktop to mobile on the same device because they filters get wrapped in a menu for mobile but the component wasn't re-rendering when it crossed that screen width threshold. This was because I was using the one-time `Browser.isMobile`, so in this PR I just switch that to our `Helpers.useWindowSize` hook so that it gets updated and the filters wrapper component is re-rendered as needed. 
[sc-12882]

use window size hook instead of one-time isMobile helper

---

client/src/components/Icons.tsx
client/src/components/PortfolioTable.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/PortfolioFilters.scss
client/src/styles/PortfolioTable.scss
client/src/styles/_button.scss
client/src/styles/_minmaxselect.scss
client/src/styles/_vars.scss

The contrast on the prev/next buttons in the portfolio table pagination bar were not meeting a11y standards, so while fixing that we made some other improvements to the design. The prev/next buttons now use icons, have clear hover and disabled states, and have 48px touch target for a11y.  We also removed the ability to select a specific page (the `page 1 of 2` is just text now).
[sc-12749]
While making these changes I needed to fix how the chevron icon was working. I had previously set a default size in the svg component but that made it difficult to override from the css, now those are there are no defaults and you set it in the css like everything else. The viewbox was also tweaked so it's a square and the icon is centered within that - this makes placement easier and ensures it stays …

update portfolio table pagination bar styles

---

client/src/components/StreetView.tsx

In #793 we switched from dynamic to static streetview images for the address page. Because the images get easily distorted switching between mobile and desktop, we fetch a new version of the image based on window size, but on initial load there is a delay in getting the screen size and so it was defaulting to mobile size then quickly switching to desktop size, causing an extra API call. 
This PR fixes the issue by just using a "loading" placeholder until the window size is known so we only make one request.

avoid extra streetview api call using "loading" placeholder

---

client/public/index.html

We're done with the short round of research using fullstory on the demo site, and are removing the snippet entirely for now because of some concerns that WOW is getting flagged on antivirus software blacklists for malware.

remove fullstory data capture snippet

---

client/package.json
client/yarn.lock

Resolve https://github.com/JustFixNYC/who-owns-what/security/dependabot/110 by bumping ejs to ^3.1.7 via resolution

add resolution for ejs ^3.1.7 for dependabot security

---

client/package.json
client/yarn.lock

update minimist to ^0.2.4 via resolution for security alerts: https://github.com/JustFixNYC/who-owns-what/security/dependabot/117 & https://github.com/JustFixNYC/who-owns-what/security/dependabot/118

update minimist to ^0.2.4 via resolution for security alert

---

client/package.json
client/yarn.lock

update immer to ^9.0.6 via resolution for security alert: https://github.com/JustFixNYC/who-owns-what/security/dependabot/61

update immer to ^9.0.6 via resolution for security alert

---

client/src/components/IndicatorsDatasets.tsx

The DOB and HPD links in indicator descriptions for the timeline are dead. DOB permits one was just moved, the others were changed a bit more, but there is now one that covers hpd complaints and violations/inspection info, so using that for both. 
[sc-13247]

update dead links to agency websites on timeline

---

client/src/components/PortfolioAlerts.tsx
client/src/components/PropertiesMap.tsx

When we launched portfolio filters we added an alert on overview map that prompts users to check out the portfolio tab to filter down the properties. We are now seeing extremely low rates of clicks on this alert, so are going to remove it along with the launch of email alerts. 
[sc-13500]

remove alert on overview map to filter portfolio

---

client/src/components/PortfolioFilters.tsx
client/src/styles/PortfolioFilters.scss

Remove the temporary "new" pill on portfolio tab from launch of filters
before:
after:
desktop | mobile
:--:|:--:
[sc-13350]

remove new pill on portfolio tab

---

client/src/components/AuthClient.ts
client/src/components/EmailAlertSignup.tsx
client/src/components/EmailInput.tsx
client/src/components/Icons.tsx
client/src/components/Login.tsx
client/src/components/PasswordInput.tsx
client/src/components/UserContext.tsx
client/src/components/UserSettingField.tsx
client/src/components/UserTypeInput.tsx
client/src/containers/ResetPasswordPage.tsx
client/src/styles/AccountSettingsPage.scss
client/src/styles/DetailView.scss
client/src/styles/EmailAlertSignup.scss
client/src/styles/EmailInput.scss
client/src/styles/ForgotPasswordPage.scss
client/src/styles/Login.scss
client/src/styles/Password.scss
client/src/styles/UserTypeInput.scss
client/src/styles/_button.scss
client/src/styles/_datatable.scss
client/src/styles/_input.scss
client/src/styles/_tabs.scss
client/src/util/helpers.ts
jfauthprovider/views.py
project/settings.py

- adds ability for account sign up to happen all within a modal from the building page
- adds a required step for account sign up, asking user type (multiple-choice or write in)
- adds verify email/ re-send email step to the end of log in/sign up flow
- refactors email input into separate component (like `PasswordInput`)
- email, password, and user type input components now work with custom `useInput` hook so that the parent can keep track of values in state. 
- This makes it easier for the parent component to hold onto input values from each step to use for error alerts and registration at the end. The same setup also helps with the input-level errors for email and whether they shown. 
- This still feels a bit overcomplicated, but we'll figure this all our for the component library and …

Multi-step log in/sign up modal, with user type

---

client/src/components/AddressSearch.tsx

I've been using Who Owns What a lot lately and really wish I could just navigate to the website and start typing without having to click into the address search field or hit tab 14 times. This should auto-focus the address input on page load.
Full disclosure, I had some issues installing the client dependencies, so I haven't tested this locally.

feature: autofocus the address search field

---

client/package.json
client/yarn.lock

Discussion: https://justfixnyc.slack.com/archives/C06H8RTJY5D/p1709657586611259
Relevant github threads: 
https://github.com/facebook/create-react-app/issues/11880
https://github.com/facebook/create-react-app/issues/11773
This seems to have resolved the issue. I guess `react-error-overlay@6.0.11` introduced it? 🤷 
I haven't had the issue reappear since I made this change locally.

Add react-error-overlay@6.0.9

---

client/src/components/EmailAlertSignup.tsx

Limit users to 15 subscriptions (fix typo from #842 that was allowing 16)

limit subscriptions to 15 (not 16)

---

client/src/components/AuthClient.ts
client/src/containers/VerifyEmailPage.tsx
jfauthprovider/urls.py
jfauthprovider/views.py

Relates to https://github.com/JustFixNYC/auth-provider/pull/30
[sc-14008]
[sc-13981]
[sc-13982]
[sc-13994]

Email verification landing page states, expiration, resend email without auth

---

client/src/components/Login.tsx

When manually toggling between Log in and Sign up flows we clear all the page-level alerts and input-level errors.
While I was at it I also added autofocus to the email input box on the Nav login/signup page. 
[sc-13922]

clear alert and input-errors on toggle login/signup

---

client/src/components/AuthClient.ts
client/src/containers/ForgotPasswordPage.tsx
client/src/containers/ResetPasswordPage.tsx
client/src/styles/ForgotPasswordPage.scss
jfauthprovider/urls.py
jfauthprovider/views.py

This PR changes the forgot/reset password flows, and goes along with changes to the auth backend in https://github.com/JustFixNYC/auth-provider/pull/31
From login you can click "forgot password?", your email is autofilled. This now has input validation to ensure a valid email (though it doesn't check for an existing account).
Submitting your email here will send a reset link to your email, and show you a success page.
Then from your email you click the link back to wow with the reset token in url params. 
We now check that token immediately when you land on the page (and while waiting it shows the standard `Loading...` placeholder. If the token is valid and active still, it changes to reset password.
This now has full input validation for the password, same as for account creation. 
If …

add reset password landing pages, validate new password inputs

---

client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx
client/src/components/UserSettingField.tsx
client/src/styles/Login.scss

On the building page, while the login/register modal is open on the page the login was being mirrored. This PR removes that by using a placeholder for on-page while the modal is open. This placeholder mimics what is there when you first land on the page (the email input). In the input box it persists whatever was in there when the modal opened, so that it doesn't update if you were to change the email in the modal. When you close the modal it swaps the placeholder for the real <Login> so the email will reset to whatever it is in state. 
And edge case we decided not to deal with at this time: if you start the on-page login process, then manually toggle to sign up in the modal. We don't persist the login as placeholder, but switch back to the email only state. …

Login mirror bug

---

client/src/containers/AccountSettingsPage.tsx
client/src/containers/UnsubscribePage.tsx
client/src/styles/UnsubscribePage.scss

Refactor the unsubscribe/manage subscriptions page that you land on via email links.
When you first land on the page there is this standard wow placeholder while it fetches your subscriptions to be able to determine what to show. 
>Note: the plural words (are/is, building/buildings) are missing from these screenshots since we need to run all the internationalization which we are doing after merging in. 
Click "manage subscriptions" link from email, while having subscriptions:
Click the unsubscribe all button from "manage subscriptions" page, or coming from email when you have 0 subscriptions:
Click on "unsubscribe" link from email when you have subscriptions:
Click the unsubscribe all button from "unsubscribe" page, or coming from email when you have 0 subscriptions:
[sc-14085]

refactor unsubscribe page

---

client/src/components/AuthClient.ts

- all emails are sent to API as lowercase. the casing remains as what user typed on the front end during the login/register process, but once redirected to account settings, it will show up as lowercase. 
- attempts to edit the email w/  different capitalizations look like this: 
[sc-13910]

Standardize email addresses as lowercase

---

client/package.json
client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx
client/src/components/SendNewLink.tsx
client/src/components/UserSettingField.tsx
client/src/containers/AccountSettingsPage.tsx
client/src/containers/ForgotPasswordPage.tsx
client/src/containers/ResetPasswordPage.tsx
client/src/containers/VerifyEmailPage.tsx
client/src/styles/AccountSettingsPage.scss
client/src/styles/SendNewLink.scss
client/src/styles/VerifyEmailPage.scss
client/src/styles/spectre/src/_utilities.scss
client/yarn.lock

This PR swaps in component-library buttons for all the email alerts work, and creates `<SendNewLink>` that toggles between a "send new link" button -> "✔️ link sent" confirmation. There are also some changes to the reset password and verify pages for expired links for consistency and to update for content doc. 
[sc-13933]
[sc-14169]

Use component library buttons in email alerts

---

client/src/components/Login.tsx

When toggling between login/signup we had issue of errors persisting, then in #865 we cleared them on toggle. But this created a new bug that allowed you to create an account with a password not meeting rules if you first toggled between login/signup. Now we just turn off the showing of errors on toggle, but don't clear the errors themselves so submit is still prevented. 
[sc-14143]

don't clear errors on login/signup toggle, only hide them

---

client/package.json
client/yarn.lock

There were some issues with alert styles getting out of scope - fixed in https://github.com/JustFixNYC/component-library/pull/23

component-library to v32.2 for alert style fixes

---

client/src/components/Login.tsx
client/src/components/UserTypeInput.tsx
client/src/styles/UserTypeInput.scss

For user type we were previously requiring a custom input when "other" was selected, this PR removes that requirement so you can check "other" and leave the input blank and it saves the type as "OTHER".
This also fixes an issue that would have had the spanish translation of user types saved on the DB, now they are always uppercase english labels for presets or the user text.
https://www.loom.com/share/7118bff1d0e14c73884d22f3e859fbde?sid=d08eb555-33dc-45c2-adf7-f69f2205dfb6
[sc-13868]

custom "other" user type not required

---

client/src/components/EmailInput.tsx
client/src/components/Login.tsx
client/src/components/PasswordInput.tsx
client/src/components/UserTypeInput.tsx
client/src/containers/App.tsx
client/src/containers/NotFoundPage.tsx
client/src/containers/NotRegisteredPage.tsx
client/src/containers/NychaPage.tsx
client/src/styles/EmailInput.scss
client/src/styles/Login.scss
client/src/styles/Password.scss
client/src/styles/UserTypeInput.scss
client/src/styles/_spacing.scss
client/src/styles/_vars.scss
client/src/styles/index.scss
client/src/styles/spectre/src/_utilities.scss

This PR adds [margin and padding utility classes](https://github.com/JustFixNYC/justfix-website/blob/master/src/styles/_custom.scss) for design-system spacing increments that we create for org site. (later this should probably move to component library)
[sc-14221]
Spectre had some of these too, so I commented those out (until we can finally move away from all spectre stuff) and updated any references to them to use our new ones instead. 
Then I used the new spacing classes to fix the input error spacing for email/password/user-type.
[sc-13887]
And finally I moved the "forgot password?" link from the password component to login to match the updated placement in figma. 
[sc-13974]
UPDATE:
Also now all the input errors deal with long messages. svg's are wrapped in div to prevent shrinking …

fix input error spacing, add util classes

---

client/src/styles/AccountSettingsPage.scss
client/src/styles/AddressToolbar.scss
client/src/styles/GetRepairs.scss
client/src/styles/SendNewLink.scss
client/src/styles/_callout.scss
client/src/styles/_typography.scss

center these two buttons
left align get repairs 
update fonts to match mock, fix alignment with "new link sent" and svg

fix alignment issues

---

client/src/components/EngagementPanel.tsx
client/src/styles/EmailInput.scss
client/src/styles/HomePage.scss
client/src/styles/Password.scss
client/src/styles/UserTypeInput.scss
client/src/styles/_minmaxselect.scss
client/src/styles/_multiselect.scss

Adds a focus state for all text inputs, matching design system (temporary until component library is ready)
[sc-13909]

add focus state outline for all text inputs

---

client/package.json
client/src/components/PortfolioTable.tsx
client/src/components/SendNewLink.tsx
client/src/components/UserSettingField.tsx
client/yarn.lock

Update to component-library v0.33.0 for [tertiary button styles](https://github.com/JustFixNYC/component-library/pull/25) and [link icons styles](https://github.com/JustFixNYC/component-library/pull/24).

update component-library for tertiary button and link icon updates

---

client/src/components/Login.tsx
client/src/i18n.tsx
client/src/styles/App.scss
client/src/styles/Password.scss
client/src/styles/_button.scss
client/src/styles/spectre/src/_base.scss

* update link focus states everywhere to match component library standard (blue outline)
* remove spectre link focus styles, make old `.button.is-text` focus style same as link until we can transition these to component library option
* add focus state to password visibility toggle [sc-14200]
* add a `<JFCLLocleLink>` to simplify usage [sc-14267]
* remove a copy/paste typo that added a ga tag to forgot password
This also fixes the focus stats for privacy/terms links on sign up [sc-13896]
A couple other example of new link focus:

add jfcl-locale-link, link focus, pw toggle focus

---

client/src/styles/EmailInput.scss
client/src/styles/Password.scss
client/src/styles/UserTypeInput.scss

On mobile safari it was zooming in on text inputs when focused. This is because the font size was < 16px, so this bumps them all up to 16px (until we can swap with component library). Testing on the preview link it does not zoom now!
desktop:
mobile:
[sc-13908]

use 16px in text inputs to prevent zooming on mobile safari

---

client/src/components/UsefulLinks.tsx
wow/forms.py
wow/sql/alerts_hpd_link.sql
wow/tests/test_views.py
wow/views.py

When the new HPD Online first launched it wouldn't allow you to link to search results based on BBL like the old version. This is important because since WOW uses BBLs for our pages, HPD uses their own "HPD building ID" and a single BBL can have multiple buildings. When there is only one building we can know that and link directly to the page, but when there are multiple we need to link to these bbl search results and the user can select the building they are interested in. 
Now that HPD allows these links, we update our own "useful links" section. 
Also in this PR I add this link (single building or search results) as an optional "indicator" on the email alerts endpoint so that we can include those in the building update emails just like useful links. 
The corresponding PR that makes use …

update HPD Online link for bbl search results, useful links and alerts api

---

client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx
client/src/containers/VerifyEmailPage.tsx
client/src/styles/Login.scss

This makes updates to content for login/signup flow for more consistency with header/sub-header text. Also remove an old step for "verify reminder" that wasn't being used. Also cuts a line about sending error report from verify page. 
[sc-14236]
Also centers the resend verify email within the sign up modal
[sc-14270]
I also clean up the login styles - nothing other than the following was added, everything else just rearranged to make it a little more clear. 
```scss
.resend-verify-label {
text-align: center;
}
.send-new-link-container {
justify-content: center;
}
```
here are all the variations:

Content updates for login flow

---

client/src/components/Login.tsx

Previous the signup flow from Nav would end after user type selection and redirect users to the account settings page. This was confusing during initial user testing since it never said anything about email verification until later it was show on building pages, also there is no need to do anything on account settings after sign up. This PR removes that redirect and shows the same "verify email" prompt as we show at the end of the on-page/in-modal sign up flow. So the final step looks like this.
[sc-14126]
(I also remove a few old references to a "verify reminder" step that doesn't exist anymore)
> Note that we'll be changing the style of this page, including adding a link to WOW homepage, as part of the "standalone page" standardized design implementation [sc-14218]

add verify step to nav signup flow, same as in modal

---

client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx

There is a weird bug with delayed user context update causing a flash, or at time persistently, showing the wrong state on the building page after adding a building via login/signup process. It would sometimes get stuck back on the beginning "check email" step when it should be subscribed/verify. And other attempted fixes would flash subscribed before verify or similar. In a rush to get this out for playbox UX testing we are just forcing a page reload at the end of login on building page and after closing the signup modal on building page. This ensures users see the correct state after the reload. Later we'll revisit and find a real solution
[sc-14242]

fix subscribed/verify/login state after adding building via login/signup

---

client/src/containers/AddressPage.tsx

replace the address page URL with the selected `detailAdddr`
Previously on WOW the address page url would always reflect the search address, and when you click on other properties in the portfolio from the map the detail page updates to that address but the URL remains the same. This caused confusion, since you could think you're copying the link for building you're currently viewing but its still the search address. Also it makes linking and using browser history navigation difficult or confusing. This will make other future changes easier, like getting back to your building after going through login/signup flow, or linking back to details from portfolio tba without needing to open a new tab or reloading the page.
[sc-14358]

update address page url for detailAddr

---

client/src/components/DetailView.tsx
client/src/components/GetRepairs.tsx
client/src/containers/VerifyEmailPage.tsx
jfauthprovider/views.py

the email verification endpoint now handles sending confirmation emails for subscriptions users created before email verification. works in conjunction with https://github.com/JustFixNYC/auth-provider/pull/38

Include origin to email verification request

---

client/src/components/EmailAlertSignup.tsx
client/src/components/EngagementPanel.tsx
client/src/components/Login.tsx
client/src/containers/HomePage.tsx
client/src/containers/VerifyEmailPage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

A collection of small updates based on feedback from early platbook ux testing.
* [update copy on verify success page](https://github.com/JustFixNYC/who-owns-what/pull/906/commits/e1bfde5874c997902a71c650bb4a907fc1115c5e) - [[sc-14438]](https://app.shortcut.com/justfixnyc/story/14438)
* [clarify password label for login vs register](https://github.com/JustFixNYC/who-owns-what/pull/906/commits/b1af1f8ebacf5b8a22521ee8d97404ab81910137) - [[sc-14439]](https://app.shortcut.com/justfixnyc/story/14439)
| login | register |
|--------|--------|
| ![image](https://github.com/JustFixNYC/who-owns-what/assets/16906516/51385f82-acf1-48c4-bb68-6a0175e75962) | ![image](https://github.com/JustFixNYC/who-owns-what/assets/16906516/cebe0fbe-a9ee-41d6-9c9e-015f47bf3880) | 
* [clarify "verify" message on …

small updates based on feedback from early Playbook UX testing

---

client/src/components/AuthClient.ts
client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx
client/src/components/PasswordInput.tsx
client/src/components/SendNewLink.tsx
client/src/components/StandalonePage.tsx
client/src/components/UserSettingField.tsx
client/src/containers/AccountSettingsPage.tsx
client/src/containers/App.tsx
client/src/containers/ForgotPasswordPage.tsx
client/src/containers/ResetPasswordPage.tsx
client/src/containers/UnsubscribePage.tsx
client/src/containers/VerifyEmailPage.tsx
client/src/state-machine.ts

Adds all the Google Tag Manager (and Amplitude) events for our tracking in GA4. 
Also makes updates to accommodate the user `id` and `type` now sent from auth provider, which we pass as params in our analytics events. 
Corresponding auth-provider pr: https://github.com/JustFixNYC/auth-provider/pull/39
[sc-14433]

Add analytics tags for email alerts

---

client/src/containers/AccountSettingsPage.tsx

When not logged in, `account/settings` redirects to `account/login`.
https://app.shortcut.com/justfixnyc/story/14498

redirect from account to login if not logged in

---

client/src/components/BuildingStatsTable.tsx
client/src/components/DetailView.tsx
client/src/components/EmailAlertSignup.tsx
client/src/components/GetRepairs.tsx
client/src/styles/DetailView.scss
client/src/styles/PropertiesMap.scss

* add back "hover for info" above building table [[sc-13591]](https://app.shortcut.com/justfixnyc/story/13591)
* right detail column max-width [[sc-14239]](https://app.shortcut.com/justfixnyc/story/14239)
* the right column max-width is 336px (per leslie in shortcut) and the map and left details column share the leftover screen width. This change only applies to screen width of tablet-landscape and up.
* copy update in LOC box [[sc-14480]](https://app.shortcut.com/justfixnyc/story/14480)
* view on google maps link style/placement [[sc-14241]](https://app.shortcut.com/justfixnyc/story/14241)
* remove "new" pill from building updates box [[sc-14478]](https://app.shortcut.com/justfixnyc/story/14478)
* removeIndicatorSuffix on timeline link …

Various small updates to the building page

---

client/src/containers/AccountSettingsPage.tsx
client/src/styles/AccountSettingsPage.scss

Adds a Logout button to the account settings page, and makes a few minor spacing/style changes:
- Adding a page rule under the "Account" label (to help provide some structure).
- Adding "You are logged in" message with a "Log out" button.
- Removing the "Log In" label that currently lives above the user email address.
- Adding a page rule above the "Building Updates" label (to more clearly separate the contact details section from the buildings section).

add logout buton to account settings, update styles

---

client/src/components/UserSettingField.tsx
client/src/containers/AccountSettingsPage.tsx
client/src/containers/App.tsx

In #912 I added a redirect from Account Settings to Login when you're not already logged in. But I'm now seeing that there's a bug with how I was checking logged in state with the usercontext which made it appear not logged in when it was just still fetching the user. This made it work ok if you are logged in and navigte to the account page, but once there if you reload the page while it's fetching the user it thinks you're logged out and so immediately redirects. I've now reverted that commit of that previous PR, so this is a redo.
Additionally, when I first attempted this redirect I added it within the account setting page itself, but I think the better way to do this is using React Router's Redirect within the specification of the Route. So this PR switches to use that approach
I think …

use router redirect for account settings page 

---

client/src/containers/LoginPage.tsx

This adds a redirect from the Login page to Account settings if you are already logged in. Also it shows a loading page while fetching the user object until we can decide whether to redirect or not. It uses a useEffect and extra state variable to track the redirect decision to avoid the problem of redirecting at the end of your login process before you can see the verification message. 
[sc-14573]

add redirect login -> account when already logged in

---

client/src/components/PasswordInput.tsx
client/src/components/UserSettingField.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

The messages.po file was a bit out of date before translations were just merged in, so this updates that. 
Also, there are some places where we have string vars that already come from i18n._() passed like: <Trans>{stringVar}</Trans> and the double lingui wrapping like this seems to break things when extracting the text for messages.po. So we should just rely on the string vars already having the translations and those get fixed there and then can be input into non-Trans tags

Lingui fixes

---

client/src/components/BuildingStatsTable.tsx

For some reason this indicator was not included in the mobile version of the table. We should add it in, and adjust the rows a bit (just for mobile) since the 4 in one row is too squished.
| before | after |
|--------|--------|
| ![image](https://github.com/JustFixNYC/who-owns-what/assets/16906516/5fe02d1b-3133-48c2-bd61-8d2777432c95) | ![image](https://github.com/JustFixNYC/who-owns-what/assets/16906516/4ca686b0-51a8-4e5f-995f-7a55ef04b9fc) |
[sc-14649]

add eviction filings to building stats table on mobile

---

client/.env
client/package.json
client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx
client/src/components/PasswordInput.tsx
client/src/components/StandalonePage.tsx
client/src/components/UserSettingField.tsx
client/src/containers/App.tsx
client/src/containers/ForgotPasswordPage.tsx
client/src/containers/ResetPasswordPage.tsx
client/src/containers/UnsubscribePage.tsx
client/src/containers/VerifyEmailPage.tsx
client/yarn.lock
project/settings.py

edit: the CTA change will be on `cta-ab-test` branch ONLY. the event param changes are what need to be merged into `master` so that our GA4 is logging the updated event param variables from the currently live split testing `master` branch. 
---
this PR adds branch name to the `eventModel` data layer variable in GTM / GA4 [sc-14639]
ideally the branch name should've been accessible at build time with `process.env.BRANCH` (see comments in [sc-14639]) but this kept returning `undefined` even after branch and deploy preview builds. I also tried accessing via `process.env.REACT_APP_BRANCH`, appending `REACT_APP_` as convention requires for apps created with `create_react_app`.  
since the out-of-the-box env variable was not accessible, I just manually set the branch variables via netlify. see …

add branch name to GTM event params for A/B testing

---

client/src/components/AuthClient.ts
jfauthprovider/views.py

two identical PRs to send the `utm_source` param
related prs:
https://github.com/JustFixNYC/auth-provider/pull/47
https://github.com/JustFixNYC/who-owns-what/pull/940
[sc-14837]

send utm_source param to auth-provider api [base: cta-ab-test] 

---

client/src/components/AuthClient.ts
jfauthprovider/views.py

two identical PRs to send the `utm_source` param
related prs:
https://github.com/JustFixNYC/auth-provider/pull/47
https://github.com/JustFixNYC/who-owns-what/pull/941
[sc-14837]

send utm_source param to auth-provider api [base: master] 

---

client/src/components/EmailAlertSignup.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

testing the following hypotheses: 
- do users read the title text and description of the feature on the buildings page? 
- once we control for the CTA that has a higher rate of clicks, will we see a significant change in the number of conversions based on the "building updates" vs. "building alerts" framing? 
A: master
- CTA: Follow Building (previously Add Building)
- copy: weekly email alerts
B: cta-ab-test (no changes)
- CTA: Follow Building
- copy: weekly building updates

A/B test Building Alerts vs. Building Updates

---

sql/create_signature_buildings.sql
wow/sql/signature_building.sql

later these will be included in the file provided by UNHP, but for now they are all active with no actions so just setting that now so we have the api structure finalized. These are used for these pills on the building pages (though the values may change as we start seeing this kind of activity in coming months) 
[sc-15043]

Add loan_status and loan_action to signature api

---

sql/create_signature_buildings.sql
wow/sql/signature_building.sql

We originally hoped to have DOB and FDNY as well, but FDNY hasn't updated their open data dataset for years, and after trying to sort out the DOB version I still don't have enough info to know which ones are still active. DOB has all vacate orders issues in the `dob_complaints` table (already in nycdb) with disposition code Y1 and Y3, but it seems those complaints get closed when the order is issued and there's no other dataset to find any further updates on those orders. I've put in questions about this and a request for more data via open data (dob is good at responding) but haven't heard back yet. 
So all that said, for now we are just using HPD vacate orders. For those we have the active status, and know if it's partial of entire building and the date it was issued. so we put those …

add hpd active vacate orders

---

wow/sql/signature_bbls.sql
wow/urls.py
wow/views.py

This removes the endpoint we thought we were going to use to filter Geosearch API results for signature BBLs. We are now using our Algolia to replace Geosearch completely for addresses and landlords

remove old api for address search

---

wow/forms.py
wow/sql/dataset_last_updated.sql
wow/urls.py
wow/views.py

Pairs with https://github.com/JustFixNYC/nycdb-k8s-loader/pull/159 which adds a table with every dataset and when it was last updated in our db. This adds a simple endpoint that takes a dataset name and returns the date it was last updated. We'll use this to provide indicator-specific last updated dates in the Signature dashboard, and it should also help for general monitoring now that there are so many dataset in there and so many are now dependencies for wow/alerts/signature.
I haven't added tests yet because I would need to add a test data builder and ran out of time. I also need to add signature api tests, so I'll do all of this as a post mvp launch task.
[sc-15116]

Add api endpoint for getting last updated date for datasets

---

sql/create_signature_building_charts.sql
sql/create_signature_buildings.sql

For HPD violations we are changing from notice of violation issue date to the inspection date, since that's the earliest date available and what we already use on WOW. This way we're minimizing the lag in data and we don't have to worry about a confusing lack of data on timeline graphs. 
[sc-15095]

use inspection date for hpd violations indicators

---

client/src/components/EmailAlertSignup.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

After running the a/b test of "get alerts" against "follow building" we're sticking with "follow building" so reverting this change
This reverts commit 259fb1a2bb0bc8ec3db03bfc1318b7349433e6cd.

Revert change of CTA to get alerts

---

project/settings.py
sql/create_signature_building_charts.sql

All our other charts go back to 2010, but we only have eviction data back to 2016/2017 (filings, executions) so we need to stop this chart here. this is also done on the front end, but wanted to do it here as well. 
https://github.com/JustFixNYC/signature-dashboard/pull/62
Also, I added the localhost for signature dashboard to the cors origins for local dev
[sc-15406]

restrict time period for eviction charts to >=2017

---

sql/create_signature_collections.sql
wow/sql/signature_portfolios.sql

While updating the UNHP data I noticed that the count of buildings was not correct because of an error in the query (forgot we don't have landlords assigned for all buildings, so was excluding those).
This fixes that query and fills in the loan_pool for those collection type records. 
[sc-15425]

fix to api query for signature portfolio cards

---

client/src/components/Indicators.tsx

a small bug we never noticed -- it was showing the default visualization name in the dropdown rather than the active visualization. current buggy behavior is recorded in this loom [link](https://www.loom.com/share/f6cf355a4ce441b5a8b1b24fda0db8c8) and the fixed behavior is in this loom [link](https://www.loom.com/share/bdb62e7a3c65409e9a087fb88f5172bf).
unfortunately the timespan dropdown's inaccuracy for rent stab units (showing "quarter" or "month" as selected when the graph is showing the "year" view) is not fixed by this

indicator dropdown shows correct timeline visualized

---

client/src/components/BuildingStatsTable.tsx

There was a bug in the condition where it short-circuited on 0 before testing for the drop - need to only exclude nulls first
[sc-15644]

overview stats table RS units drop to zero in red text

---

client/src/components/DetailView.tsx
client/src/containers/NotRegisteredPage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

The HPD registration datasets on the Open Data portal haven't been updated since June 1, but are supposed to be automatically each month. We are talking with HPD about getting things updated, but in the meantime we wanted to put a note on the WOW building pages where we usually put the latest registration date explaining that we don't have the data and to look on HPD Online where they have the up-to-date info. Hopefully we'll have the data updated soon and then we can just revert this commit. See [slack thread](https://justfixnyc.slack.com/archives/CCWHGAR9C/p1729525389206699) for discussion with Joel. 
[sc-15724]

add note for delayed hpd reg data

---

client/src/styles/BuildingStatsTable.scss

- unbolded indicator names
- info icon is bigger and a lighter color to match signature dashboard

overview table style changes

---

client/src/components/DetailView.tsx
client/src/containers/NotRegisteredPage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po

In #976 we added a temporary note about delayed HPD registration data. After reaching out they have posted the new data and we have everything updated on our end, so we can remove the note.

Remove hpd registration data delay note

---

client/src/components/APIClient.ts

For all addresses pages the URL has the street address, and we first input those into a request to Geosearch to get the BBL, then use the BBL for a request to our own WOW api for the data to populate the page. This happens for every load of an address page, and it completely separate from our use of Geosearch for the address autocomplete/search bar on the home page. 
Since we always have the complete address (boro, number, streetname) in the URL for an address page we had just taken all of that and put that into the Geosearch api (eg. `101 MANHATTAN AVENUE, MANHATTAN`) and take the first property in the response. However, in some rare cases the first result option is incorrect. For example for this address the first result given is for the same address but in brooklyn, and so we populate …

ensure selected geosearch result matched on borough

---

sql/create_bldgs_table.sql
wow/sql/address_indicatorhistory.sql

From Praks:
>Noting that for [this building](https://whoownswhat.justfix.org/en/address/BROOKLYN/123/MELROSE%20STREET) while the overview tab says RS units is NA, the timeline tab shows all 468 units since 2020 (assuming because 421 a starts this year) 
Since it's a new building it's not in the old RS table, and we were doing a left join so all the later years were missing. 
Separate I also noticed a typo in the RS timeline query that was leaving out 2019
[sc-16095]

Rs data fix

---

sql/create_gce_screener.sql

After creating the separate file for the temporary tables used by both the `gce_screener` and `gce_eligibility` tables, there was still some old code that is no longer being used, so this just deletes those sections

remove old unused code from gce_screener sql query

---

sql/create_gce_common.sql
sql/create_gce_screener.sql

Add Certificate of Occupancy records from DOB NOW system (added to nycdb in https://github.com/nycdb/nycdb/pull/371) to the Good Cause tables
[sc-16216]

add dob_now_cofo data and remove jobtype (unused)

---

wow/sql/dataset_tracker.sql
wow/urls.py
wow/views.py

We want to set up a dashboard display dataset update status and daily cron job script to check for out-of-date datasets, so this API endpoint returns all the information about datasets recorded via nycdb-k8s-loader and the manually created/maintained table of expected dataset schedules. 
They may be some changes to this set up, but just wanted to get a first pass of this up and running now.
[sc-15800]

add API endpoint for dataset tracker info for sending alerts

---

client/src/components/APIClient.ts
client/src/components/APIDataTypes.ts
client/src/components/DatasetTrackerTable.tsx
client/src/components/PortfolioTable.tsx
client/src/containers/DevPage.tsx
client/src/styles/DatasetTrackerTable.scss
wow/sql/dataset_tracker.sql

Uses the new API endpoint (https://github.com/JustFixNYC/who-owns-what/pull/990) to add a simple table of all our datasets (nycdb and custom jobs) and when they were last updated and highlighting if any are late. 
I kept the table extremely simple for now, without any interactively or extra data aside from what's in the API response.
Later I think it would be nice to add the ability to click on a row and reveal an extra row with a list of all the tables that dataset includes, what projects it's used in (wow, signature, etc.), and links to the the NYCDB wiki documentation page the sources datasets so we can check for problems on the open data portal. Unfortunately all this meta data isn't accessible from the NYCDB code itself, so I think I might just build this out manually in a static …

add dataset update tracker table to /dev page

---

sql/create_gce_common.sql
sql/create_gce_screener.sql

We now get all the owner party names from acris for the 5 documents we find for each property, and compare the names between the search address and the related properties to look for common names, and then use this flag to help prioritize/sort the related properties on the portfolio guide page. 
frontend companion PR: https://github.com/JustFixNYC/gce-screener/pull/118

add acris party name match to gce related property data

---

sql/create_gce_eligibility.sql
sql/create_gce_eligibility_maps.sql
who-owns-what.yml

A Housing Data Coalition project of mapping Good Cause eligibility data (https://github.com/kfinn/good-cause-map) requires some aggregations of the BBL-level `gce_eligiblity` table for displaying results by hexagons (of various sizes for different zoom levels) and various political districts.

add sql for gce eligibility district aggregations for HDC map

---

client/src/components/BuildingStatsTable.tsx
client/src/components/PropertiesMap.tsx

I noticed that we're getting console errors about invalid html syntax for the new buildn stats table on overview page. It was missing a `<tbody>` within the `<table>`.
Also I've added a type for a mapbox option that is needed to avoid errors when we make a change to the version for district-maps  (doing it now just helps when switching back and forth between wow main and district-alerts for local development)
[sc-16155]

Fix invalid html syntax for building stats table table

---

client/src/containers/HomePage.tsx

A while back we needed to get data on all the addresses searched on WOW and we needed to geocode all the addresses which was a pain. This adds BBL as an event param to the wow address search GA4 tag so we can skip that step in future. 
[sc-16168]

add bbl event param to wow address search GA4 tag

---

who-owns-what.yml

The tables for good cause eligibility (not used in the screener website, but for data analysis and sharing with partners) aren't working because they depend on the table `pluto_latest_districts` which is a one-off table we've created in the DB but isn't an nycdb or other k8s-loader recognized job so it fails tests. So for now I'm just removing these tables from the list that are created, and later I think we'll need to add the sql for creating `pluto_latest_districts` to an nycdb dataset or another k8s-loader job in the who-owns-what repo like goodcause itself.

remove GCE eligibility tables with unmet table dependency

---

sql/create_gce_screener.sql

Somehow there were a ton of rows getting created that had no bbl, and so when aggregating all the related properties data by bbl (in the temp table immediately after this one being edited) there is one row for the null bbl that had an array being aggregated with millions of elements and it broke everything. Unfortunately I'm still not totally sure how these additional rows were getting created, but there are no duplicates among the other non-null bbl records. I could trace it down to this one join, and left a comment about it, but I don't see how this could happening, because when I do the same query without that last join there are no null-bbl rows, and the table being joined has no null-bbl rows, yet somehow after adding in that final join the result has a lot of null-bbl rows. Even …

remove rows without bbl from gce_screener related properties

---

wow/sql/alerts_district_vacate_order.sql

the `hpd_link` was missing from the vacate orders api for area alerts. it is already create in the indicators table so just adding it to the select
[sc-16355]

add hpd_link to vacate orders api for area alerts

---

wow/sql/alerts_district_litigation.sql
wow/sql/alerts_district_sale.sql
wow/sql/alerts_district_vacate_order.sql

For area alerts emails we now want to include the most recent month of data, based on when the dataset was last updated rather than the date we are sending the email. So this edits the api queries to use the table with datasets' last updated dates to create the date filer. 
Companion PR on auth-provider for email: https://github.com/JustFixNYC/auth-provider/pull/85
[sc-16374]

Area alert API for sales and litigations for month relative to updated date

---

wow/sql/alerts_district.sql

Updates our main Area Alerts API to exclude buildings from the Portfolio to Watch section if they don't have any data values to display. They are still included in the `area_bbls` count, but the building objects are included in the result.
Related to changes for the portfolio section messages in < PR TBA >

exclude portfolio to watch buildings with no values

---

client/src/data/district-types.json
client/src/styles/DistrictAlertsPage.scss
client/src/util/helpers.ts
sql/create_districts_geom.sql
sql/create_indicators_table.sql
wow/forms.py
wow/sql/alerts_district.sql
wow/sql/alerts_district_litigation.sql
wow/sql/alerts_district_sale.sql
wow/sql/alerts_district_vacate_order.sql
wow/views.py

We decided they weren't a priority, and it's better to start with a smaller list of districts at launch and add more later if there's interest.
Also bumps up the font size on the save selections button

Remove congressional districts from area alerts

---

client/src/components/UserContext.tsx

This only happens sometimes, but after subscribing to an area while logged in the user is automatically sent to the account settings page where all area subscriptions should be listed but sometimes it won't be there until the page is refreshed. 
This was because the api request to subscribe to the area was sent out but sometimes it wouldn't complete before the user got sent to the setting page. We confirmed this by looking at the devtools "waterfall" overview graph on the network tab and you can see the sequencing of the requests. This was because of a missing `await` within the `UserContext.subscribeDistrict`, and once that was added and the navigation to setting page is delayed ontil the subscription is complete every works as intended now.
[sc-16406]

user state not updating sometimes on account page after area alerts subscription

---

client/src/components/EmailInput.tsx

We got some feedback from a user that their `me.com` email was marked as invalid preventing them from signing up. We actually intended to allow 2-char domains but the way it was written (I think to allow subdomains?) it wasn't actually working that way. 
I looked around at a bunch of example email validation regexes, and saw the advice that you can really only know for sure by attempting a send, but this one seemed to work for the cases we need and had a lot of up votes, so it seems good for our purposes. 
https://stackoverflow.com/a/46181/7051239

update email validation regex on signup to allow 2-char domains

---

client/src/data/district-types.json
client/src/util/helpers.ts
sql/create_districts_geom.sql
sql/create_indicators_table.sql
wow/forms.py
wow/sql/alerts_district.sql
wow/sql/alerts_district_litigation.sql
wow/sql/alerts_district_sale.sql
wow/sql/alerts_district_vacate_order.sql
wow/views.py

We're trying to limit the number of area types in the dropdown, and boroughs seem so large they are unlikely to be used - but we can always add it back later upon request
[sc-16417]

remove borough as area alerts option

---

Dockerfile

A new version of [Geosupport](https://www.nyc.gov/content/planning/pages/resources/geocoding/geosupport-desktop-edition) has been released, 25a, and this updates the local development dockerfile for the new download file. It's good to keep this updated regularly so that it keeps pace with the version of PLUTO we get in `pluto_latest`.
The important place for this to be updated is on nycdb-k8s-loader, since that dockerfile is actually used for the cron jobs that run the WOW job that uses geosupport to geocode HPD registration contact business addresses. see https://github.com/JustFixNYC/nycdb-k8s-loader/pull/207

update dev dockerfile for latest geosupport

---

sql/create_gce_common.sql

We got some feedback from a user on GoodCauseNYC about a case where a 2010 CofO that appears on the DOB site was not being found on GoodCauseNYC and so gave an incorrect "covered" result. We discovered that this is because for some older CofO records the BBL from the time no longer exists (since they change when lots of split/merged) but in many cases using the BIN you can join with [PAD](https://www.nyc.gov/content/planning/pages/resources/datasets/pad) to get the current BBL that the bin is associated with now. 
Can we confirmed that this works for the case they found:  `SELECT * FROM wow_indicators WHERE bbl = '4005660136';`
[sc-16412]

update bbls of cofos with no longer existing bbls

---

client/public/index.html
client/src/components/DetailView.tsx
client/src/components/PropertiesSummary.tsx
client/src/components/StreetView.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/DetailView.scss
client/src/styles/PropertiesSummary.scss

The API for these streetview images is quite expensive, and the quality has been declining (now common to get images inside businesses etc) so we've decided to completely remove it from the site for now. We have already done so for the desktop building page, so now we are removing it from mobile building pages and the summary tab for desktop and mobile.
[sc-16440]

remove streetview image from building pages (mobile) and summary tab (mobile/desktop)

---

client/src/components/DistrictMap.tsx
client/src/styles/DistrictAlertsPage.scss
client/src/styles/_vars.scss
wow/sql/alerts_district.sql

- Update map colors w/ JF purple
- Fix CTE order in `alerts_district.sql` that was breaking an edge case 
- Example: zip code 10464
- With the previous order, `top_5` was pulling buildings with no activity and ranking them as 4th  and 5th. The `first_shared_portfolio` CTE would then select either 4th or 5th building as one to calculate the portfolio buildings on. All was good until this data was sent to the auth-provider, which expects the portfolio buildings and at least one of the ranked buildings to share a portfolio_id, which was not happening. This was breaking an email send.

Area alerts final VQA

---

sql/create_gce_eligibility.sql
who-owns-what.yml

In #1007 we temporarily had to remove the GCE eligibility and map tables because they rely on `pluto_latest_districts` which was a one-off table we created directly on the DB outside of our usual nycdb process and that broke tests. We have since updated nycdb to add this dataset with a new pattern for datasets without source data and with dependencies on other nycdb datasets in https://github.com/nycdb/nycdb/pull/386. So now we can add these tables back to the goodcause job to run on k8s.
Companion PR: https://github.com/JustFixNYC/nycdb-k8s-loader/pull/216
[sc-16362]

add back temporarily removed gce eligibility tables

---

sql/create_gce_common.sql
sql/create_gce_eligibility.sql

For some internal analysis of GCE responses we wanted to see how often users were ineligible for GCE because of a recent CofO that was for an Alteration rather than new building, which was a technical mistake in the way the law was written. So to do this it's easiest to add the CofO type to the `gce_eligibility` table we often use for analysis (not used for the actual website).
Analysis code where this is used https://github.com/JustFixNYC/requests/blob/main/gce-internal/gce-responses-analytics.R#L159-L214

add CofO type to gce_eligibility table

---

client/src/components/EmailAlertSignup.tsx
client/src/components/Login.tsx
client/src/components/ToastAlert.tsx
client/src/containers/AccountSettingsPage.tsx
client/src/containers/DistrictAlertsPage.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/AccountSettingsPage.scss
client/src/styles/EmailAlertSignup.scss
client/src/styles/_toastalert.scss

Adds a alert "toast" to the top of the account settings page that appears/disappears from the top when you are directed to the settings page after completing an area alerts subscription. The copy of the alert differs if you are already logged in vs when you start the signup from a logged out state and complete registration/login to complete the subscription flow. There is also a text button in the alert to "manage" subscriptions that scrolls down to the area alerts section of the page, since it's sometimes out of view if you have a bunch of building alert subscriptions already. This uses a ref and `scrollIntoView` instead of an anchor link as originally planned because that was breaking on safari.
This copies the existing implementation we used for the toast alert on building pages when …

Area subscription toast

---

client/src/components/AuthClient.ts
client/src/components/Login.tsx
client/src/components/PhoneNumberInput.tsx
client/src/components/UserContext.tsx
client/src/components/UserTypeInput.tsx
client/src/locales/en/messages.po
client/src/locales/es/messages.po
client/src/styles/PhoneNumberInput.scss
client/src/util/helpers.ts
jfauthprovider/views.py

Adds a new (optional) step to account creation to capture user phone numbers. Borrows input UI phone number formatting from gce-screener. Updates all the authclient/views backend logic to reflect changes to auth-provider. Updates the Login component to add the new step (in all cases, via nav, building, or area alerts), and adds a "step 1 of 3" progress to the top of the login module during registration.
Companion PR on auth-provider: https://github.com/JustFixNYC/auth-provider/pull/111
[sc-16527]

Capture user phone number (optionally) during account registration
